<script lang="ts">
	/**
	 * Budget page - Category breakdown with donut chart
	 *
	 * 🤖 Generated by Ralph
	 */
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import DoughnutChart from '$lib/components/charts/DoughnutChart.svelte';
	import type { BudgetData, ParentCategorySummary, CategorySummary } from './+page.server';

	let { data }: { data: BudgetData } = $props();

	// Period selector
	const periods = [
		{ value: 'month', label: 'Ce mois' },
		{ value: 'last_month', label: 'Mois dernier' },
		{ value: 'quarter', label: 'Trimestre' },
		{ value: 'year', label: 'Année' }
	];

	let selectedPeriod = $derived(data.period.key);

	function handlePeriodChange(period: string) {
		const url = new URL($page.url);
		url.searchParams.set('period', period);
		goto(url.toString(), { replaceState: true, noScroll: true });
	}

	// Expanded categories state
	let expandedCategories = $state<Set<string>>(new Set());

	function toggleCategory(categoryId: string) {
		const newExpanded = new Set(expandedCategories);
		if (newExpanded.has(categoryId)) {
			newExpanded.delete(categoryId);
		} else {
			newExpanded.add(categoryId);
		}
		expandedCategories = newExpanded;
	}

	// View toggle: expenses or income
	let viewMode = $state<'expenses' | 'income'>('expenses');

	// Formatting functions
	function formatCurrency(value: number): string {
		return value.toLocaleString('fr-FR', {
			style: 'currency',
			currency: 'EUR',
			minimumFractionDigits: 0,
			maximumFractionDigits: 0
		});
	}

	function formatCurrencyDetailed(value: number): string {
		return value.toLocaleString('fr-FR', {
			style: 'currency',
			currency: 'EUR',
			minimumFractionDigits: 2,
			maximumFractionDigits: 2
		});
	}

	function formatPercent(value: number): string {
		return `${value.toFixed(1)}%`;
	}

	// Chart data
	const chartData = $derived.by(() => {
		const categories = viewMode === 'expenses' ? data.expenses_by_parent : data.income_by_parent;
		return categories.slice(0, 8).map((cat) => ({
			label: cat.category_name,
			value: cat.total_amount,
			color: cat.category_color
		}));
	});

	// Current data based on view mode
	const currentCategories = $derived(
		viewMode === 'expenses' ? data.expenses_by_parent : data.income_by_parent
	);

	const currentTotal = $derived(
		viewMode === 'expenses' ? data.totals.expenses : data.totals.income
	);

	// Count categories with data
	const categoriesWithData = $derived(currentCategories.length);
</script>

<div class="budget-page">
	<header class="page-header">
		<div class="header-left">
			<h1>Budget</h1>
			<span class="header-period">{data.period.label}</span>
		</div>
	</header>

	<!-- Period Selector -->
	<div class="period-selector">
		{#each periods as period}
			<button
				class="period-btn"
				class:active={selectedPeriod === period.value}
				onclick={() => handlePeriodChange(period.value)}
			>
				{period.label}
			</button>
		{/each}
	</div>

	<!-- KPI Cards -->
	<section class="kpi-section">
		<div class="kpi-cards">
			<div class="kpi-card expenses">
				<div class="kpi-icon danger">
					<svg
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						aria-hidden="true"
					>
						<polyline points="22 17 13.5 8.5 8.5 13.5 2 7" />
						<polyline points="16 17 22 17 22 11" />
					</svg>
				</div>
				<div class="kpi-content">
					<span class="kpi-label">Dépenses</span>
					<span class="kpi-value text-danger">{formatCurrency(data.totals.expenses)}</span>
				</div>
			</div>

			<div class="kpi-card income">
				<div class="kpi-icon success">
					<svg
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						aria-hidden="true"
					>
						<polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
						<polyline points="16 7 22 7 22 13" />
					</svg>
				</div>
				<div class="kpi-content">
					<span class="kpi-label">Revenus</span>
					<span class="kpi-value text-success">{formatCurrency(data.totals.income)}</span>
				</div>
			</div>

			<div
				class="kpi-card net"
				class:positive={data.totals.net >= 0}
				class:negative={data.totals.net < 0}
			>
				<div class="kpi-icon" class:success={data.totals.net >= 0} class:danger={data.totals.net < 0}>
					<svg
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						aria-hidden="true"
					>
						<line x1="12" y1="1" x2="12" y2="23" />
						<path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
					</svg>
				</div>
				<div class="kpi-content">
					<span class="kpi-label">Solde</span>
					<span
						class="kpi-value"
						class:text-success={data.totals.net >= 0}
						class:text-danger={data.totals.net < 0}
					>
						{data.totals.net >= 0 ? '+' : ''}{formatCurrency(data.totals.net)}
					</span>
				</div>
			</div>
		</div>
	</section>

	<!-- Main Content: Chart + Categories -->
	<div class="main-content">
		<!-- View Toggle -->
		<div class="view-toggle" role="group" aria-label="Type de transactions">
			<button
				class="toggle-btn"
				class:active={viewMode === 'expenses'}
				onclick={() => (viewMode = 'expenses')}
				aria-pressed={viewMode === 'expenses'}
			>
				<svg
					width="16"
					height="16"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					aria-hidden="true"
				>
					<polyline points="22 17 13.5 8.5 8.5 13.5 2 7" />
				</svg>
				Dépenses
			</button>
			<button
				class="toggle-btn"
				class:active={viewMode === 'income'}
				onclick={() => (viewMode = 'income')}
				aria-pressed={viewMode === 'income'}
			>
				<svg
					width="16"
					height="16"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					aria-hidden="true"
				>
					<polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
				</svg>
				Revenus
			</button>
		</div>

		<div class="content-grid">
			<!-- Chart Section -->
			<div class="chart-section">
				{#if chartData.length > 0}
					<DoughnutChart
						data={chartData}
						title={viewMode === 'expenses' ? 'Répartition des dépenses' : 'Répartition des revenus'}
					/>
				{:else}
					<div class="empty-chart">
						<div class="empty-icon" aria-hidden="true">
							<svg
								width="48"
								height="48"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="1.5"
							>
								<circle cx="12" cy="12" r="10" />
								<path d="M12 6v6l4 2" />
							</svg>
						</div>
						<span class="empty-text">Aucune donnée pour cette période</span>
					</div>
				{/if}
			</div>

			<!-- Categories List -->
			<div class="categories-section">
				<div class="section-header">
					<h2 class="section-title">Par catégorie</h2>
					<span class="category-count">{categoriesWithData} catégorie{categoriesWithData > 1 ? 's' : ''}</span>
				</div>

				{#if currentCategories.length > 0}
					<div class="categories-list">
						{#each currentCategories as category, index}
							{@const isExpanded = expandedCategories.has(category.category_id)}
							{@const hasChildren = category.children.length > 1 || (category.children.length === 1 && category.children[0].parent_id !== null)}
							<div
								class="category-item"
								style="--anim-delay: {index * 0.03}s"
							>
								<button
									class="category-header"
									onclick={() => hasChildren && toggleCategory(category.category_id)}
									class:expandable={hasChildren}
									aria-expanded={hasChildren ? isExpanded : undefined}
								>
									<div class="category-identity">
										<span
											class="category-icon"
											style="background-color: {category.category_color}20; color: {category.category_color}"
										>
											{category.category_icon}
										</span>
										<span class="category-name">{category.category_name}</span>
										{#if hasChildren}
											<span class="expand-icon" class:expanded={isExpanded} aria-hidden="true">
												<svg
													width="16"
													height="16"
													viewBox="0 0 24 24"
													fill="none"
													stroke="currentColor"
													stroke-width="2"
												>
													<polyline points="6 9 12 15 18 9" />
												</svg>
											</span>
										{/if}
									</div>
									<div class="category-values">
										<span class="category-amount">{formatCurrencyDetailed(category.total_amount)}</span>
										<div class="category-bar-container">
											<div
												class="category-bar"
												style="width: {Math.min(category.percentage, 100)}%; background-color: {category.category_color}"
											></div>
										</div>
										<span class="category-percent">{formatPercent(category.percentage)}</span>
									</div>
								</button>

								{#if isExpanded && hasChildren}
									<div class="category-children">
										{#each category.children as child}
											{#if child.parent_id !== null}
												<div class="child-item">
													<div class="child-identity">
														<span class="child-icon">{child.category_icon}</span>
														<span class="child-name">{child.category_name}</span>
													</div>
													<div class="child-values">
														<span class="child-amount">{formatCurrencyDetailed(child.total_amount)}</span>
														<span class="child-percent">{formatPercent(child.percentage)}</span>
													</div>
												</div>
											{/if}
										{/each}
									</div>
								{/if}
							</div>
						{/each}
					</div>
				{:else}
					<div class="empty-categories">
						<span>Aucune transaction catégorisée</span>
					</div>
				{/if}

				<!-- Uncategorized section -->
				{#if data.uncategorized.count > 0}
					{@const uncategorizedAmount = viewMode === 'expenses' ? data.uncategorized.total_expenses : data.uncategorized.total_income}
					{#if uncategorizedAmount > 0}
						<div class="uncategorized-section">
							<div class="uncategorized-header">
								<div class="uncategorized-identity">
									<span class="uncategorized-icon">❓</span>
									<span class="uncategorized-name">Non catégorisé</span>
								</div>
								<div class="uncategorized-values">
									<span class="uncategorized-amount">{formatCurrencyDetailed(uncategorizedAmount)}</span>
									<span class="uncategorized-count">{data.uncategorized.count} transaction{data.uncategorized.count > 1 ? 's' : ''}</span>
								</div>
							</div>
							<a href="/transactions?uncategorized=true" class="uncategorized-link">
								Voir et catégoriser
								<svg
									width="14"
									height="14"
									viewBox="0 0 24 24"
									fill="none"
									stroke="currentColor"
									stroke-width="2"
									aria-hidden="true"
								>
									<polyline points="9 18 15 12 9 6" />
								</svg>
							</a>
						</div>
					{/if}
				{/if}
			</div>
		</div>
	</div>
</div>

<style>
	.budget-page {
		max-width: var(--content-max-width);
		margin: 0 auto;
		display: flex;
		flex-direction: column;
		gap: var(--spacing-6);
	}

	.page-header {
		display: flex;
		justify-content: space-between;
		align-items: flex-start;
		animation: fadeInUp 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) forwards;
	}

	.header-left {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-1);
	}

	.page-header h1 {
		font-size: var(--font-size-3xl);
		font-weight: var(--font-weight-bold);
		color: var(--color-text-primary);
		letter-spacing: var(--letter-spacing-tight);
	}

	.header-period {
		font-size: var(--font-size-sm);
		color: var(--color-text-muted);
		text-transform: capitalize;
	}

	/* Period Selector */
	.period-selector {
		display: flex;
		gap: var(--spacing-1);
		background: var(--color-bg-elevated);
		padding: var(--spacing-1);
		border-radius: var(--radius-lg);
		border: 1px solid var(--color-border);
		animation: fadeInUp 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) 0.05s forwards;
		opacity: 0;
		width: fit-content;
	}

	.period-btn {
		padding: var(--spacing-2) var(--spacing-4);
		border-radius: var(--radius-md);
		font-size: var(--font-size-sm);
		font-weight: var(--font-weight-medium);
		color: var(--color-text-muted);
		background: transparent;
		transition:
			color var(--transition-fast),
			background-color var(--transition-fast);
		border: none;
		cursor: pointer;
		min-height: 44px;
	}

	.period-btn:hover {
		color: var(--color-text-secondary);
		background: var(--color-bg-subtle);
	}

	.period-btn.active {
		background: var(--color-bg-card);
		color: var(--color-primary-500);
	}

	/* KPI Section */
	.kpi-section {
		animation: fadeInUp 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) 0.1s forwards;
		opacity: 0;
	}

	.kpi-cards {
		display: grid;
		grid-template-columns: repeat(3, 1fr);
		gap: var(--spacing-4);
	}

	.kpi-card {
		background: var(--color-bg-card);
		border-radius: var(--radius-xl);
		border: 1px solid var(--color-border);
		padding: var(--spacing-5);
		display: flex;
		align-items: flex-start;
		gap: var(--spacing-4);
		transition:
			background-color var(--transition-fast),
			border-color var(--transition-fast);
	}

	.kpi-card:hover {
		background: var(--color-bg-card-hover);
		border-color: var(--color-border-hover);
	}

	.kpi-card.net.positive {
		background: linear-gradient(135deg, rgba(16, 185, 129, 0.05) 0%, rgba(16, 185, 129, 0.02) 100%);
		border-color: rgba(16, 185, 129, 0.2);
	}

	.kpi-card.net.negative {
		background: linear-gradient(135deg, rgba(239, 68, 68, 0.05) 0%, rgba(239, 68, 68, 0.02) 100%);
		border-color: rgba(239, 68, 68, 0.2);
	}

	.kpi-icon {
		width: 48px;
		height: 48px;
		border-radius: var(--radius-lg);
		display: flex;
		align-items: center;
		justify-content: center;
		flex-shrink: 0;
	}

	.kpi-icon.success {
		background: rgba(16, 185, 129, 0.1);
		color: var(--color-success-500);
	}

	.kpi-icon.danger {
		background: var(--color-danger-50);
		color: var(--color-danger-500);
	}

	.kpi-content {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-1);
	}

	.kpi-label {
		font-size: var(--font-size-sm);
		color: var(--color-text-tertiary);
		text-transform: uppercase;
		letter-spacing: var(--letter-spacing-caps);
	}

	.kpi-value {
		font-size: var(--font-size-2xl);
		font-weight: var(--font-weight-bold);
		color: var(--color-text-primary);
	}

	.text-success {
		color: var(--color-success-500);
	}

	.text-danger {
		color: var(--color-danger-500);
	}

	/* Main Content */
	.main-content {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-4);
		animation: fadeInUp 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) 0.15s forwards;
		opacity: 0;
	}

	/* View Toggle */
	.view-toggle {
		display: flex;
		gap: var(--spacing-1);
		background: var(--color-bg-elevated);
		padding: var(--spacing-1);
		border-radius: var(--radius-lg);
		border: 1px solid var(--color-border);
		width: fit-content;
	}

	.toggle-btn {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
		padding: var(--spacing-2) var(--spacing-4);
		border-radius: var(--radius-md);
		font-size: var(--font-size-sm);
		font-weight: var(--font-weight-medium);
		color: var(--color-text-muted);
		background: transparent;
		transition:
			color var(--transition-fast),
			background-color var(--transition-fast);
		border: none;
		cursor: pointer;
		min-height: 44px;
	}

	.toggle-btn:hover {
		color: var(--color-text-secondary);
		background: var(--color-bg-subtle);
	}

	.toggle-btn.active {
		background: var(--color-bg-card);
		color: var(--color-primary-500);
	}

	/* Content Grid */
	.content-grid {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: var(--spacing-6);
	}

	/* Chart Section */
	.chart-section {
		min-height: 360px;
	}

	.empty-chart {
		background: var(--color-bg-card);
		border-radius: var(--radius-xl);
		border: 1px dashed var(--color-border);
		padding: var(--spacing-12);
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: var(--spacing-3);
		min-height: 360px;
	}

	.empty-icon {
		color: var(--color-text-muted);
		opacity: 0.5;
	}

	.empty-text {
		font-size: var(--font-size-base);
		color: var(--color-text-muted);
	}

	/* Categories Section */
	.categories-section {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-4);
	}

	.section-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.section-title {
		font-size: var(--font-size-lg);
		font-weight: var(--font-weight-semibold);
		color: var(--color-text-primary);
	}

	.category-count {
		font-size: var(--font-size-sm);
		color: var(--color-text-muted);
		background: var(--color-bg-subtle);
		padding: var(--spacing-1) var(--spacing-3);
		border-radius: var(--radius-full);
	}

	.categories-list {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-2);
	}

	.category-item {
		background: var(--color-bg-card);
		border-radius: var(--radius-lg);
		border: 1px solid var(--color-border);
		overflow: hidden;
		animation: fadeInUp 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) calc(0.15s + var(--anim-delay)) forwards;
		opacity: 0;
	}

	.category-header {
		width: 100%;
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: var(--spacing-4);
		gap: var(--spacing-4);
		background: transparent;
		border: none;
		text-align: left;
		transition: background-color var(--transition-fast);
	}

	.category-header.expandable {
		cursor: pointer;
	}

	.category-header.expandable:hover {
		background: var(--color-bg-card-hover);
	}

	.category-identity {
		display: flex;
		align-items: center;
		gap: var(--spacing-3);
		min-width: 0;
	}

	.category-icon {
		width: 36px;
		height: 36px;
		border-radius: var(--radius-md);
		display: flex;
		align-items: center;
		justify-content: center;
		font-size: var(--font-size-lg);
		flex-shrink: 0;
	}

	.category-name {
		font-size: var(--font-size-base);
		font-weight: var(--font-weight-medium);
		color: var(--color-text-primary);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.expand-icon {
		color: var(--color-text-muted);
		transition: transform var(--transition-fast);
		flex-shrink: 0;
	}

	.expand-icon.expanded {
		transform: rotate(180deg);
	}

	.category-values {
		display: flex;
		align-items: center;
		gap: var(--spacing-3);
		flex-shrink: 0;
	}

	.category-amount {
		font-size: var(--font-size-base);
		font-weight: var(--font-weight-semibold);
		color: var(--color-text-primary);
		min-width: 100px;
		text-align: right;
	}

	.category-bar-container {
		width: 80px;
		height: 6px;
		background: var(--color-bg-subtle);
		border-radius: var(--radius-full);
		overflow: hidden;
	}

	.category-bar {
		height: 100%;
		border-radius: var(--radius-full);
		transition: width var(--transition-normal);
	}

	.category-percent {
		font-size: var(--font-size-sm);
		color: var(--color-text-muted);
		min-width: 48px;
		text-align: right;
	}

	/* Category Children */
	.category-children {
		border-top: 1px solid var(--color-border);
		padding: var(--spacing-2) var(--spacing-4);
		background: var(--color-bg-subtle);
	}

	.child-item {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: var(--spacing-2) var(--spacing-3);
		gap: var(--spacing-4);
		border-radius: var(--radius-md);
		transition: background-color var(--transition-fast);
	}

	.child-item:hover {
		background: var(--color-bg-card);
	}

	.child-identity {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
	}

	.child-icon {
		font-size: var(--font-size-sm);
	}

	.child-name {
		font-size: var(--font-size-sm);
		color: var(--color-text-secondary);
	}

	.child-values {
		display: flex;
		align-items: center;
		gap: var(--spacing-3);
	}

	.child-amount {
		font-size: var(--font-size-sm);
		font-weight: var(--font-weight-medium);
		color: var(--color-text-primary);
	}

	.child-percent {
		font-size: var(--font-size-xs);
		color: var(--color-text-muted);
		min-width: 40px;
		text-align: right;
	}

	.empty-categories {
		padding: var(--spacing-8);
		text-align: center;
		color: var(--color-text-muted);
		background: var(--color-bg-card);
		border-radius: var(--radius-lg);
		border: 1px dashed var(--color-border);
	}

	/* Uncategorized Section */
	.uncategorized-section {
		margin-top: var(--spacing-4);
		padding: var(--spacing-4);
		background: rgba(245, 158, 11, 0.05);
		border: 1px dashed var(--color-warning-300);
		border-radius: var(--radius-lg);
	}

	.uncategorized-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: var(--spacing-3);
	}

	.uncategorized-identity {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
	}

	.uncategorized-icon {
		font-size: var(--font-size-lg);
	}

	.uncategorized-name {
		font-size: var(--font-size-base);
		font-weight: var(--font-weight-medium);
		color: var(--color-text-secondary);
	}

	.uncategorized-values {
		display: flex;
		flex-direction: column;
		align-items: flex-end;
		gap: var(--spacing-0-5);
	}

	.uncategorized-amount {
		font-size: var(--font-size-base);
		font-weight: var(--font-weight-semibold);
		color: var(--color-warning-600);
	}

	.uncategorized-count {
		font-size: var(--font-size-xs);
		color: var(--color-text-muted);
	}

	.uncategorized-link {
		display: inline-flex;
		align-items: center;
		gap: var(--spacing-1);
		font-size: var(--font-size-sm);
		color: var(--color-primary-500);
		text-decoration: none;
		font-weight: var(--font-weight-medium);
		transition: color var(--transition-fast);
	}

	.uncategorized-link:hover {
		color: var(--color-primary-600);
	}

	@keyframes fadeInUp {
		from {
			opacity: 0;
			transform: translateY(12px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	/* Responsive */
	@media (max-width: 1024px) {
		.content-grid {
			grid-template-columns: 1fr;
		}

		.chart-section {
			order: 2;
		}

		.categories-section {
			order: 1;
		}
	}

	@media (max-width: 768px) {
		.budget-page {
			gap: var(--spacing-5);
		}

		.page-header h1 {
			font-size: var(--font-size-2xl);
		}

		.period-selector {
			width: 100%;
			flex-wrap: wrap;
		}

		.period-btn {
			flex: 1;
			min-width: calc(50% - var(--spacing-1));
			justify-content: center;
		}

		.kpi-cards {
			grid-template-columns: 1fr;
			gap: var(--spacing-3);
		}

		.kpi-card {
			padding: var(--spacing-4);
		}

		.kpi-icon {
			width: 40px;
			height: 40px;
		}

		.kpi-value {
			font-size: var(--font-size-xl);
		}

		.view-toggle {
			width: 100%;
		}

		.toggle-btn {
			flex: 1;
			justify-content: center;
		}

		.section-title {
			font-size: var(--font-size-base);
		}

		.category-header {
			padding: var(--spacing-3);
			flex-wrap: wrap;
		}

		.category-icon {
			width: 32px;
			height: 32px;
			font-size: var(--font-size-base);
		}

		.category-values {
			width: 100%;
			justify-content: flex-end;
			margin-top: var(--spacing-2);
		}

		.category-bar-container {
			display: none;
		}

		.uncategorized-header {
			flex-direction: column;
			align-items: flex-start;
			gap: var(--spacing-2);
		}

		.uncategorized-values {
			align-items: flex-start;
		}
	}

	@media (max-width: 375px) {
		.kpi-icon {
			width: 36px;
			height: 36px;
		}

		.kpi-value {
			font-size: var(--font-size-lg);
		}

		.kpi-label {
			font-size: var(--font-size-xs);
		}

		.category-amount {
			font-size: var(--font-size-sm);
			min-width: auto;
		}
	}

	/* Reduced motion */
	@media (prefers-reduced-motion: reduce) {
		.category-item,
		.page-header,
		.period-selector,
		.kpi-section,
		.main-content {
			animation: none;
			opacity: 1;
		}

		.expand-icon {
			transition: none;
		}

		.category-bar {
			transition: none;
		}
	}
</style>
