/**
 * API endpoints for transaction category management
 *
 * GET /api/transactions/[id]/category - returns the category assigned to a transaction
 * PUT /api/transactions/[id]/category - manually assigns a category to a transaction
 *
 * 🤖 Generated by Ralph
 */

import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { CategoryRepositoryImpl } from '@infrastructure/repositories/CategoryRepository';
import { TransactionRepositoryImpl } from '@infrastructure/database/repositories/TransactionRepository';
import { UniqueId } from '@domain/shared/UniqueId';
import {
	CategorySource,
	createTransactionCategoryAssignment
} from '@domain/budget/TransactionCategoryAssignment';

const categoryRepository = new CategoryRepositoryImpl();
const transactionRepository = new TransactionRepositoryImpl();

/**
 * GET /api/transactions/[id]/category
 * Returns the category assignment for a transaction, including category details
 */
export const GET: RequestHandler = async ({ params }) => {
	const { id } = params;
	const transactionId = UniqueId.fromString(id);

	// Check if transaction exists
	const transaction = await transactionRepository.findById(transactionId);
	if (!transaction) {
		throw error(404, 'Transaction not found');
	}

	// Get category assignment
	const assignment = await categoryRepository.findAssignmentByTransactionId(transactionId);

	if (!assignment) {
		return json({
			transaction_id: id,
			category: null,
			source: null,
			confidence: null,
			assigned_at: null
		});
	}

	// Get category details
	const category = await categoryRepository.findCategoryById(assignment.categoryId);

	return json({
		transaction_id: id,
		category: category
			? {
					id: category.id.toString(),
					name: category.name,
					icon: category.icon,
					color: category.color,
					parent_id: category.parentId?.toString() ?? null
				}
			: null,
		source: assignment.source,
		confidence: assignment.confidence,
		assigned_at: assignment.assignedAt.toISOString()
	});
};

/**
 * PUT /api/transactions/[id]/category
 * Manually assigns a category to a transaction (sets source='manual')
 *
 * Request body: { category_id: string }
 */
export const PUT: RequestHandler = async ({ params, request }) => {
	const { id } = params;
	const transactionId = UniqueId.fromString(id);

	// Check if transaction exists
	const transaction = await transactionRepository.findById(transactionId);
	if (!transaction) {
		throw error(404, 'Transaction not found');
	}

	// Parse request body
	let body: { category_id?: string };
	try {
		body = await request.json();
	} catch {
		throw error(400, 'Invalid JSON body');
	}

	if (!body.category_id) {
		throw error(400, 'category_id is required');
	}

	const categoryId = UniqueId.fromString(body.category_id);

	// Check if category exists
	const category = await categoryRepository.findCategoryById(categoryId);
	if (!category) {
		throw error(404, 'Category not found');
	}

	// Create manual assignment (always overwrites existing)
	const assignment = createTransactionCategoryAssignment({
		transactionId,
		categoryId,
		source: CategorySource.MANUAL,
		confidence: 1.0
	});

	await categoryRepository.saveAssignment(assignment);

	return json({
		transaction_id: id,
		category: {
			id: category.id.toString(),
			name: category.name,
			icon: category.icon,
			color: category.color,
			parent_id: category.parentId?.toString() ?? null
		},
		source: CategorySource.MANUAL,
		confidence: 1.0,
		assigned_at: assignment.assignedAt.toISOString()
	});
};
