/**
 * Seed script for budget categories (hierarchical) and category rules
 *
 * This script inserts:
 * - 10 root (parent) categories: Logement, Alimentation, Transport, Loisirs, Sante, Revenus, Epargne, Impots, Banque, Autre
 * - Sub-categories for each parent (2-level hierarchy)
 * - Bank category mappings (Caisse d'Epargne, Boursorama -> internal categories)
 *
 * Run with: npx tsx src/scripts/seed-categories.ts
 *
 * Generated by Ralph
 */

import { execute, closeDatabase } from '../infrastructure/database/turso';

// =====================================================
// Category IDs (stable for referencing)
// =====================================================

const ROOT_IDS = {
	LOGEMENT: 'cat-logement',
	ALIMENTATION: 'cat-alimentation',
	TRANSPORT: 'cat-transport',
	LOISIRS: 'cat-loisirs',
	SANTE: 'cat-sante',
	REVENUS: 'cat-revenus',
	EPARGNE: 'cat-epargne',
	IMPOTS: 'cat-impots',
	BANQUE: 'cat-banque',
	AUTRE: 'cat-autre'
} as const;

// =====================================================
// Root Categories Definition
// =====================================================

interface CategoryDef {
	id: string;
	name: string;
	icon: string;
	color: string;
	children: Array<{ id: string; name: string; icon: string }>;
}

const CATEGORIES: CategoryDef[] = [
	{
		id: ROOT_IDS.LOGEMENT,
		name: 'Logement',
		icon: 'home',
		color: '#EF4444',
		children: [
			{ id: 'cat-loyer', name: 'Loyer', icon: 'key' },
			{ id: 'cat-charges', name: 'Charges', icon: 'bolt' },
			{ id: 'cat-electricite', name: 'Electricite', icon: 'zap' },
			{ id: 'cat-gaz', name: 'Gaz', icon: 'flame' },
			{ id: 'cat-eau', name: 'Eau', icon: 'droplet' },
			{ id: 'cat-internet', name: 'Internet/TV', icon: 'wifi' },
			{ id: 'cat-assurance-habitation', name: 'Assurance habitation', icon: 'shield' },
			{ id: 'cat-travaux', name: 'Travaux', icon: 'hammer' },
			{ id: 'cat-ameublement', name: 'Ameublement', icon: 'sofa' },
			{ id: 'cat-copropriete', name: 'Copropriete', icon: 'building' }
		]
	},
	{
		id: ROOT_IDS.ALIMENTATION,
		name: 'Alimentation',
		icon: 'utensils',
		color: '#F97316',
		children: [
			{ id: 'cat-courses', name: 'Courses', icon: 'shopping-cart' },
			{ id: 'cat-restaurant', name: 'Restaurant', icon: 'utensils' },
			{ id: 'cat-fast-food', name: 'Fast-food', icon: 'burger' },
			{ id: 'cat-bar-cafe', name: 'Bar/Cafe', icon: 'coffee' },
			{ id: 'cat-livraison', name: 'Livraison', icon: 'bike' }
		]
	},
	{
		id: ROOT_IDS.TRANSPORT,
		name: 'Transport',
		icon: 'car',
		color: '#3B82F6',
		children: [
			{ id: 'cat-carburant', name: 'Carburant', icon: 'fuel' },
			{ id: 'cat-peage', name: 'Peage', icon: 'road' },
			{ id: 'cat-parking', name: 'Parking', icon: 'parking' },
			{ id: 'cat-assurance-auto', name: 'Assurance auto', icon: 'shield-check' },
			{ id: 'cat-entretien-auto', name: 'Entretien auto', icon: 'wrench' },
			{ id: 'cat-transports-commun', name: 'Transports en commun', icon: 'train' },
			{ id: 'cat-taxi-vtc', name: 'Taxi/VTC', icon: 'taxi' },
			{ id: 'cat-avion', name: 'Avion', icon: 'plane' },
			{ id: 'cat-train', name: 'Train', icon: 'train' },
			{ id: 'cat-location-voiture', name: 'Location voiture', icon: 'car-rental' }
		]
	},
	{
		id: ROOT_IDS.LOISIRS,
		name: 'Loisirs',
		icon: 'gamepad',
		color: '#8B5CF6',
		children: [
			{ id: 'cat-sorties', name: 'Sorties', icon: 'ticket' },
			{ id: 'cat-sport', name: 'Sport', icon: 'dumbbell' },
			{ id: 'cat-vacances', name: 'Vacances', icon: 'palm-tree' },
			{ id: 'cat-abonnements', name: 'Abonnements', icon: 'repeat' },
			{ id: 'cat-culture', name: 'Culture', icon: 'book' },
			{ id: 'cat-jeux', name: 'Jeux', icon: 'gamepad' },
			{ id: 'cat-cadeaux', name: 'Cadeaux', icon: 'gift' },
			{ id: 'cat-shopping', name: 'Shopping', icon: 'shopping-bag' },
			{ id: 'cat-high-tech', name: 'High-tech', icon: 'smartphone' }
		]
	},
	{
		id: ROOT_IDS.SANTE,
		name: 'Sante',
		icon: 'heart-pulse',
		color: '#EC4899',
		children: [
			{ id: 'cat-medecin', name: 'Medecin', icon: 'stethoscope' },
			{ id: 'cat-pharmacie', name: 'Pharmacie', icon: 'pill' },
			{ id: 'cat-mutuelle', name: 'Mutuelle', icon: 'shield-plus' },
			{ id: 'cat-dentiste', name: 'Dentiste', icon: 'tooth' },
			{ id: 'cat-opticien', name: 'Opticien', icon: 'glasses' },
			{ id: 'cat-hopital', name: 'Hopital', icon: 'hospital' }
		]
	},
	{
		id: ROOT_IDS.REVENUS,
		name: 'Revenus',
		icon: 'wallet',
		color: '#10B981',
		children: [
			{ id: 'cat-salaire', name: 'Salaire', icon: 'briefcase' },
			{ id: 'cat-freelance', name: 'Freelance', icon: 'laptop' },
			{ id: 'cat-dividendes', name: 'Dividendes', icon: 'trending-up' },
			{ id: 'cat-loyers-perçus', name: 'Loyers percus', icon: 'key' },
			{ id: 'cat-remboursement', name: 'Remboursement', icon: 'rotate-ccw' },
			{ id: 'cat-aides', name: 'Aides/Allocations', icon: 'hand-coins' },
			{ id: 'cat-ventes', name: 'Ventes', icon: 'tag' },
			{ id: 'cat-autres-revenus', name: 'Autres revenus', icon: 'plus-circle' }
		]
	},
	{
		id: ROOT_IDS.EPARGNE,
		name: 'Epargne',
		icon: 'piggy-bank',
		color: '#22C55E',
		children: [
			{ id: 'cat-livret-a', name: 'Livret A', icon: 'book' },
			{ id: 'cat-pel', name: 'PEL', icon: 'home' },
			{ id: 'cat-assurance-vie', name: 'Assurance vie', icon: 'umbrella' },
			{ id: 'cat-pea', name: 'PEA', icon: 'trending-up' },
			{ id: 'cat-cto', name: 'CTO', icon: 'chart-line' },
			{ id: 'cat-crypto', name: 'Crypto', icon: 'bitcoin' },
			{ id: 'cat-autres-epargne', name: 'Autres epargne', icon: 'wallet' }
		]
	},
	{
		id: ROOT_IDS.IMPOTS,
		name: 'Impots',
		icon: 'landmark',
		color: '#64748B',
		children: [
			{ id: 'cat-ir', name: 'Impot sur le revenu', icon: 'file-text' },
			{ id: 'cat-taxe-fonciere', name: 'Taxe fonciere', icon: 'home' },
			{ id: 'cat-taxe-habitation', name: 'Taxe habitation', icon: 'door-open' },
			{ id: 'cat-csg-crds', name: 'CSG/CRDS', icon: 'percent' },
			{ id: 'cat-autres-impots', name: 'Autres impots', icon: 'file-minus' }
		]
	},
	{
		id: ROOT_IDS.BANQUE,
		name: 'Banque',
		icon: 'building-2',
		color: '#6366F1',
		children: [
			{ id: 'cat-frais-bancaires', name: 'Frais bancaires', icon: 'receipt' },
			{ id: 'cat-interets', name: 'Interets', icon: 'percent' },
			{ id: 'cat-retrait-dab', name: 'Retrait DAB', icon: 'banknote' },
			{ id: 'cat-virement-interne', name: 'Virement interne', icon: 'arrow-left-right' },
			{ id: 'cat-credit', name: 'Credit', icon: 'credit-card' }
		]
	},
	{
		id: ROOT_IDS.AUTRE,
		name: 'Autre',
		icon: 'more-horizontal',
		color: '#9CA3AF',
		children: [
			{ id: 'cat-divers', name: 'Divers', icon: 'box' },
			{ id: 'cat-non-categorise', name: 'Non categorise', icon: 'help-circle' }
		]
	}
];

// =====================================================
// Bank Category Mappings (CE and Boursorama -> internal)
// =====================================================

// Caisse d'Epargne categories
const CE_CATEGORY_MAP: Record<string, string> = {
	// Alimentation
	'Alimentation / Epicerie': 'cat-courses',
	'Alimentation - Epicerie': 'cat-courses',
	'Alimentation-Epicerie': 'cat-courses',
	Alimentation: 'cat-courses',
	Restaurant: 'cat-restaurant',
	'Restauration rapide': 'cat-fast-food',
	// Transport
	Transport: 'cat-transports-commun',
	Carburant: 'cat-carburant',
	'Auto / Moto': 'cat-entretien-auto',
	Peage: 'cat-peage',
	Stationnement: 'cat-parking',
	// Logement
	Logement: 'cat-loyer',
	Loyer: 'cat-loyer',
	'Energie / Eau': 'cat-charges',
	Electricite: 'cat-electricite',
	'Telecom / Internet': 'cat-internet',
	// Loisirs
	Loisirs: 'cat-sorties',
	'Culture / Sorties': 'cat-culture',
	Vacances: 'cat-vacances',
	Sport: 'cat-sport',
	// Sante
	Sante: 'cat-medecin',
	Pharmacie: 'cat-pharmacie',
	Mutuelle: 'cat-mutuelle',
	// Revenus
	Salaire: 'cat-salaire',
	Revenus: 'cat-salaire',
	// Impots
	Impots: 'cat-ir',
	// Banque
	'Frais bancaires': 'cat-frais-bancaires',
	'Retrait DAB': 'cat-retrait-dab',
	Virement: 'cat-virement-interne',
	// Autres
	Divers: 'cat-divers',
	'Non catégorisé': 'cat-non-categorise'
};

// Boursorama categories
const BOURSO_CATEGORY_MAP: Record<string, string> = {
	// Alimentation
	'Alimentation et restauration': 'cat-courses',
	'Supermarche': 'cat-courses',
	'Supermarchés & Epiceries': 'cat-courses',
	'Restaurants & Bars': 'cat-restaurant',
	'Fast food': 'cat-fast-food',
	Boulangerie: 'cat-courses',
	// Transport
	'Transports': 'cat-transports-commun',
	'Essence & Carburant': 'cat-carburant',
	'Péages': 'cat-peage',
	'Parking': 'cat-parking',
	'Auto - Moto': 'cat-entretien-auto',
	'Taxis & VTC': 'cat-taxi-vtc',
	// Logement
	'Logement': 'cat-loyer',
	'Loyers': 'cat-loyer',
	'Energie & Services': 'cat-charges',
	'Téléphone & Internet': 'cat-internet',
	// Loisirs
	'Loisirs & Sorties': 'cat-sorties',
	'Shopping': 'cat-shopping',
	'Achats & Shopping': 'cat-shopping',
	'Sport': 'cat-sport',
	'Vacances & Voyages': 'cat-vacances',
	'Abonnements': 'cat-abonnements',
	// Sante
	'Santé': 'cat-medecin',
	'Pharmacie': 'cat-pharmacie',
	// Revenus
	'Salaires': 'cat-salaire',
	'Revenus': 'cat-salaire',
	'Allocations & Aides': 'cat-aides',
	'Remboursements': 'cat-remboursement',
	// Epargne
	'Epargne': 'cat-livret-a',
	'Placements': 'cat-assurance-vie',
	// Impots
	'Impôts & Taxes': 'cat-ir',
	// Banque
	'Frais bancaires': 'cat-frais-bancaires',
	'Retrait espèces': 'cat-retrait-dab',
	'Virements': 'cat-virement-interne',
	'Intérêts': 'cat-interets',
	// Autres
	'Divers': 'cat-divers',
	'Non catégorisé': 'cat-non-categorise',
	'Opérations non catégorisées': 'cat-non-categorise'
};

// =====================================================
// Seed Functions
// =====================================================

async function seedCategories(): Promise<void> {
	console.log('Inserting categories...\n');

	for (const category of CATEGORIES) {
		// Insert root category
		await execute(
			`INSERT OR REPLACE INTO categories (id, name, parent_id, icon, color, created_at)
			VALUES (?, ?, ?, ?, ?, datetime('now'))`,
			[category.id, category.name, null, category.icon, category.color]
		);
		console.log(`  [ROOT] ${category.name} (${category.icon}, ${category.color})`);

		// Insert children with same color as parent
		for (const child of category.children) {
			await execute(
				`INSERT OR REPLACE INTO categories (id, name, parent_id, icon, color, created_at)
				VALUES (?, ?, ?, ?, ?, datetime('now'))`,
				[child.id, child.name, category.id, child.icon, category.color]
			);
			console.log(`    - ${child.name} (${child.icon})`);
		}
	}

	// Count total
	const totalChildren = CATEGORIES.reduce((sum, cat) => sum + cat.children.length, 0);
	console.log(`\n  ${CATEGORIES.length} root categories inserted`);
	console.log(`  ${totalChildren} sub-categories inserted`);
}

async function seedBankCategoryMappings(): Promise<void> {
	console.log('\nInserting bank category mappings as rules...\n');

	let ruleCount = 0;

	// CE mappings (source filter: caisse_epargne)
	console.log('  Caisse d\'Epargne mappings:');
	for (const [bankCategory, internalCategoryId] of Object.entries(CE_CATEGORY_MAP)) {
		const ruleId = `rule-ce-${ruleCount++}`;
		// Use exact match pattern for bank categories
		const pattern = `^${escapeRegex(bankCategory)}$`;

		await execute(
			`INSERT OR REPLACE INTO category_rules (id, category_id, pattern, priority, source_filter, is_active, created_at)
			VALUES (?, ?, ?, ?, ?, ?, datetime('now'))`,
			[ruleId, internalCategoryId, pattern, 100, 'caisse_epargne', 1]
		);
		console.log(`    "${bankCategory}" -> ${internalCategoryId}`);
	}

	// Boursorama mappings (source filter: boursorama)
	console.log('\n  Boursorama mappings:');
	for (const [bankCategory, internalCategoryId] of Object.entries(BOURSO_CATEGORY_MAP)) {
		const ruleId = `rule-bourso-${ruleCount++}`;
		const pattern = `^${escapeRegex(bankCategory)}$`;

		await execute(
			`INSERT OR REPLACE INTO category_rules (id, category_id, pattern, priority, source_filter, is_active, created_at)
			VALUES (?, ?, ?, ?, ?, ?, datetime('now'))`,
			[ruleId, internalCategoryId, pattern, 100, 'boursorama', 1]
		);
		console.log(`    "${bankCategory}" -> ${internalCategoryId}`);
	}

	console.log(`\n  ${ruleCount} bank category mapping rules inserted`);
}

function escapeRegex(str: string): string {
	return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

async function verifySeededData(): Promise<void> {
	console.log('\nVerification...\n');

	// Count categories
	const rootResult = await execute('SELECT COUNT(*) as count FROM categories WHERE parent_id IS NULL');
	const rootCount = (rootResult.rows[0] as unknown as { count: number }).count;

	const childResult = await execute('SELECT COUNT(*) as count FROM categories WHERE parent_id IS NOT NULL');
	const childCount = (childResult.rows[0] as unknown as { count: number }).count;

	console.log(`  Root categories: ${rootCount}`);
	console.log(`  Sub-categories: ${childCount}`);
	console.log(`  Total categories: ${rootCount + childCount}`);

	// Count rules
	const rulesResult = await execute('SELECT COUNT(*) as count FROM category_rules');
	const rulesCount = (rulesResult.rows[0] as unknown as { count: number }).count;
	console.log(`  Category rules: ${rulesCount}`);

	// Show category hierarchy
	console.log('\n  Category hierarchy:');
	const hierarchyResult = await execute(`
		SELECT
			p.name as parent_name,
			p.color as parent_color,
			c.name as child_name
		FROM categories p
		LEFT JOIN categories c ON c.parent_id = p.id
		WHERE p.parent_id IS NULL
		ORDER BY p.name, c.name
	`);

	let currentParent = '';
	for (const row of hierarchyResult.rows) {
		const r = row as unknown as { parent_name: string; parent_color: string; child_name: string | null };
		if (r.parent_name !== currentParent) {
			currentParent = r.parent_name;
			console.log(`\n    ${r.parent_name} (${r.parent_color})`);
		}
		if (r.child_name) {
			console.log(`      - ${r.child_name}`);
		}
	}
}

// =====================================================
// Main
// =====================================================

async function main(): Promise<void> {
	console.log('Seeding categories and bank mappings...\n');

	try {
		await seedCategories();
		await seedBankCategoryMappings();
		await verifySeededData();

		console.log('\n Seed completed successfully!');
	} catch (error) {
		console.error('\n Seed failed:', error);
		throw error;
	} finally {
		await closeDatabase();
	}
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
