/**
 * Seed script for budget categories (hierarchical) and category rules
 *
 * This script inserts:
 * - 10 root (parent) categories: Logement, Alimentation, Transport, Loisirs, Sante, Revenus, Epargne, Impots, Banque, Autre
 * - Sub-categories for each parent (2-level hierarchy)
 * - Bank category mappings (Caisse d'Epargne, Boursorama -> internal categories)
 *
 * Run with: npx tsx src/scripts/seed-categories.ts
 *
 * Generated by Ralph
 */

import { execute, closeDatabase } from '../infrastructure/database/turso';

// =====================================================
// Category IDs (stable for referencing)
// =====================================================

const ROOT_IDS = {
	LOGEMENT: 'cat-logement',
	ALIMENTATION: 'cat-alimentation',
	TRANSPORT: 'cat-transport',
	LOISIRS: 'cat-loisirs',
	SANTE: 'cat-sante',
	REVENUS: 'cat-revenus',
	EPARGNE: 'cat-epargne',
	IMPOTS: 'cat-impots',
	BANQUE: 'cat-banque',
	AUTRE: 'cat-autre'
} as const;

// =====================================================
// Root Categories Definition
// =====================================================

interface CategoryDef {
	id: string;
	name: string;
	icon: string;
	color: string;
	children: Array<{ id: string; name: string; icon: string }>;
}

const CATEGORIES: CategoryDef[] = [
	{
		id: ROOT_IDS.LOGEMENT,
		name: 'Logement',
		icon: 'home',
		color: '#EF4444',
		children: [
			{ id: 'cat-loyer', name: 'Loyer', icon: 'key' },
			{ id: 'cat-charges', name: 'Charges', icon: 'bolt' },
			{ id: 'cat-electricite', name: 'Electricite', icon: 'zap' },
			{ id: 'cat-gaz', name: 'Gaz', icon: 'flame' },
			{ id: 'cat-eau', name: 'Eau', icon: 'droplet' },
			{ id: 'cat-internet', name: 'Internet/TV', icon: 'wifi' },
			{ id: 'cat-assurance-habitation', name: 'Assurance habitation', icon: 'shield' },
			{ id: 'cat-travaux', name: 'Travaux', icon: 'hammer' },
			{ id: 'cat-ameublement', name: 'Ameublement', icon: 'sofa' },
			{ id: 'cat-copropriete', name: 'Copropriete', icon: 'building' }
		]
	},
	{
		id: ROOT_IDS.ALIMENTATION,
		name: 'Alimentation',
		icon: 'utensils',
		color: '#F97316',
		children: [
			{ id: 'cat-courses', name: 'Courses', icon: 'shopping-cart' },
			{ id: 'cat-restaurant', name: 'Restaurant', icon: 'utensils' },
			{ id: 'cat-fast-food', name: 'Fast-food', icon: 'burger' },
			{ id: 'cat-bar-cafe', name: 'Bar/Cafe', icon: 'coffee' },
			{ id: 'cat-livraison', name: 'Livraison', icon: 'bike' }
		]
	},
	{
		id: ROOT_IDS.TRANSPORT,
		name: 'Transport',
		icon: 'car',
		color: '#3B82F6',
		children: [
			{ id: 'cat-carburant', name: 'Carburant', icon: 'fuel' },
			{ id: 'cat-peage', name: 'Peage', icon: 'road' },
			{ id: 'cat-parking', name: 'Parking', icon: 'parking' },
			{ id: 'cat-assurance-auto', name: 'Assurance auto', icon: 'shield-check' },
			{ id: 'cat-entretien-auto', name: 'Entretien auto', icon: 'wrench' },
			{ id: 'cat-transports-commun', name: 'Transports en commun', icon: 'train' },
			{ id: 'cat-taxi-vtc', name: 'Taxi/VTC', icon: 'taxi' },
			{ id: 'cat-avion', name: 'Avion', icon: 'plane' },
			{ id: 'cat-train', name: 'Train', icon: 'train' },
			{ id: 'cat-location-voiture', name: 'Location voiture', icon: 'car-rental' }
		]
	},
	{
		id: ROOT_IDS.LOISIRS,
		name: 'Loisirs',
		icon: 'gamepad',
		color: '#8B5CF6',
		children: [
			{ id: 'cat-sorties', name: 'Sorties', icon: 'ticket' },
			{ id: 'cat-sport', name: 'Sport', icon: 'dumbbell' },
			{ id: 'cat-vacances', name: 'Vacances', icon: 'palm-tree' },
			{ id: 'cat-abonnements', name: 'Abonnements', icon: 'repeat' },
			{ id: 'cat-culture', name: 'Culture', icon: 'book' },
			{ id: 'cat-jeux', name: 'Jeux', icon: 'gamepad' },
			{ id: 'cat-cadeaux', name: 'Cadeaux', icon: 'gift' },
			{ id: 'cat-shopping', name: 'Shopping', icon: 'shopping-bag' },
			{ id: 'cat-high-tech', name: 'High-tech', icon: 'smartphone' }
		]
	},
	{
		id: ROOT_IDS.SANTE,
		name: 'Sante',
		icon: 'heart-pulse',
		color: '#EC4899',
		children: [
			{ id: 'cat-medecin', name: 'Medecin', icon: 'stethoscope' },
			{ id: 'cat-pharmacie', name: 'Pharmacie', icon: 'pill' },
			{ id: 'cat-mutuelle', name: 'Mutuelle', icon: 'shield-plus' },
			{ id: 'cat-dentiste', name: 'Dentiste', icon: 'tooth' },
			{ id: 'cat-opticien', name: 'Opticien', icon: 'glasses' },
			{ id: 'cat-hopital', name: 'Hopital', icon: 'hospital' }
		]
	},
	{
		id: ROOT_IDS.REVENUS,
		name: 'Revenus',
		icon: 'wallet',
		color: '#10B981',
		children: [
			{ id: 'cat-salaire', name: 'Salaire', icon: 'briefcase' },
			{ id: 'cat-freelance', name: 'Freelance', icon: 'laptop' },
			{ id: 'cat-dividendes', name: 'Dividendes', icon: 'trending-up' },
			{ id: 'cat-loyers-perçus', name: 'Loyers percus', icon: 'key' },
			{ id: 'cat-remboursement', name: 'Remboursement', icon: 'rotate-ccw' },
			{ id: 'cat-aides', name: 'Aides/Allocations', icon: 'hand-coins' },
			{ id: 'cat-ventes', name: 'Ventes', icon: 'tag' },
			{ id: 'cat-autres-revenus', name: 'Autres revenus', icon: 'plus-circle' }
		]
	},
	{
		id: ROOT_IDS.EPARGNE,
		name: 'Epargne',
		icon: 'piggy-bank',
		color: '#22C55E',
		children: [
			{ id: 'cat-livret-a', name: 'Livret A', icon: 'book' },
			{ id: 'cat-pel', name: 'PEL', icon: 'home' },
			{ id: 'cat-assurance-vie', name: 'Assurance vie', icon: 'umbrella' },
			{ id: 'cat-pea', name: 'PEA', icon: 'trending-up' },
			{ id: 'cat-cto', name: 'CTO', icon: 'chart-line' },
			{ id: 'cat-crypto', name: 'Crypto', icon: 'bitcoin' },
			{ id: 'cat-autres-epargne', name: 'Autres epargne', icon: 'wallet' }
		]
	},
	{
		id: ROOT_IDS.IMPOTS,
		name: 'Impots',
		icon: 'landmark',
		color: '#64748B',
		children: [
			{ id: 'cat-ir', name: 'Impot sur le revenu', icon: 'file-text' },
			{ id: 'cat-taxe-fonciere', name: 'Taxe fonciere', icon: 'home' },
			{ id: 'cat-taxe-habitation', name: 'Taxe habitation', icon: 'door-open' },
			{ id: 'cat-csg-crds', name: 'CSG/CRDS', icon: 'percent' },
			{ id: 'cat-autres-impots', name: 'Autres impots', icon: 'file-minus' }
		]
	},
	{
		id: ROOT_IDS.BANQUE,
		name: 'Banque',
		icon: 'building-2',
		color: '#6366F1',
		children: [
			{ id: 'cat-frais-bancaires', name: 'Frais bancaires', icon: 'receipt' },
			{ id: 'cat-interets', name: 'Interets', icon: 'percent' },
			{ id: 'cat-retrait-dab', name: 'Retrait DAB', icon: 'banknote' },
			{ id: 'cat-virement-interne', name: 'Virement interne', icon: 'arrow-left-right' },
			{ id: 'cat-credit', name: 'Credit', icon: 'credit-card' }
		]
	},
	{
		id: ROOT_IDS.AUTRE,
		name: 'Autre',
		icon: 'more-horizontal',
		color: '#9CA3AF',
		children: [
			{ id: 'cat-divers', name: 'Divers', icon: 'box' },
			{ id: 'cat-non-categorise', name: 'Non categorise', icon: 'help-circle' }
		]
	}
];

// =====================================================
// Bank Category Mappings (CE and Boursorama -> internal)
// =====================================================

// Caisse d'Epargne categories
const CE_CATEGORY_MAP: Record<string, string> = {
	// Alimentation
	'Alimentation / Epicerie': 'cat-courses',
	'Alimentation - Epicerie': 'cat-courses',
	'Alimentation-Epicerie': 'cat-courses',
	Alimentation: 'cat-courses',
	Restaurant: 'cat-restaurant',
	'Restauration rapide': 'cat-fast-food',
	// Transport
	Transport: 'cat-transports-commun',
	Carburant: 'cat-carburant',
	'Auto / Moto': 'cat-entretien-auto',
	Peage: 'cat-peage',
	Stationnement: 'cat-parking',
	// Logement
	Logement: 'cat-loyer',
	Loyer: 'cat-loyer',
	'Energie / Eau': 'cat-charges',
	Electricite: 'cat-electricite',
	'Telecom / Internet': 'cat-internet',
	// Loisirs
	Loisirs: 'cat-sorties',
	'Culture / Sorties': 'cat-culture',
	Vacances: 'cat-vacances',
	Sport: 'cat-sport',
	// Sante
	Sante: 'cat-medecin',
	Pharmacie: 'cat-pharmacie',
	Mutuelle: 'cat-mutuelle',
	// Revenus
	Salaire: 'cat-salaire',
	Revenus: 'cat-salaire',
	// Impots
	Impots: 'cat-ir',
	// Banque
	'Frais bancaires': 'cat-frais-bancaires',
	'Retrait DAB': 'cat-retrait-dab',
	Virement: 'cat-virement-interne',
	// Autres
	Divers: 'cat-divers',
	'Non catégorisé': 'cat-non-categorise'
};

// Boursorama categories
const BOURSO_CATEGORY_MAP: Record<string, string> = {
	// Alimentation
	'Alimentation et restauration': 'cat-courses',
	'Supermarche': 'cat-courses',
	'Supermarchés & Epiceries': 'cat-courses',
	'Restaurants & Bars': 'cat-restaurant',
	'Fast food': 'cat-fast-food',
	Boulangerie: 'cat-courses',
	// Transport
	'Transports': 'cat-transports-commun',
	'Essence & Carburant': 'cat-carburant',
	'Péages': 'cat-peage',
	'Parking': 'cat-parking',
	'Auto - Moto': 'cat-entretien-auto',
	'Taxis & VTC': 'cat-taxi-vtc',
	// Logement
	'Logement': 'cat-loyer',
	'Loyers': 'cat-loyer',
	'Energie & Services': 'cat-charges',
	'Téléphone & Internet': 'cat-internet',
	// Loisirs
	'Loisirs & Sorties': 'cat-sorties',
	'Shopping': 'cat-shopping',
	'Achats & Shopping': 'cat-shopping',
	'Sport': 'cat-sport',
	'Vacances & Voyages': 'cat-vacances',
	'Abonnements': 'cat-abonnements',
	// Sante
	'Santé': 'cat-medecin',
	'Pharmacie': 'cat-pharmacie',
	// Revenus
	'Salaires': 'cat-salaire',
	'Revenus': 'cat-salaire',
	'Allocations & Aides': 'cat-aides',
	'Remboursements': 'cat-remboursement',
	// Epargne
	'Epargne': 'cat-livret-a',
	'Placements': 'cat-assurance-vie',
	// Impots
	'Impôts & Taxes': 'cat-ir',
	// Banque
	'Frais bancaires': 'cat-frais-bancaires',
	'Retrait espèces': 'cat-retrait-dab',
	'Virements': 'cat-virement-interne',
	'Intérêts': 'cat-interets',
	// Autres
	'Divers': 'cat-divers',
	'Non catégorisé': 'cat-non-categorise',
	'Opérations non catégorisées': 'cat-non-categorise'
};

// =====================================================
// Regex Categorization Rules (for description matching)
// =====================================================
// These rules match transaction descriptions (libellés) and are used
// primarily for Crédit Mutuel (which doesn't have native categories)
// and as fallback for other banks.
// Priority: lower number = higher priority (checked first)

interface RegexRule {
	pattern: string; // Regex pattern (case insensitive by default)
	categoryId: string;
	priority: number; // Lower = higher priority
}

const REGEX_RULES: RegexRule[] = [
	// ===== ALIMENTATION - Courses (priority 10-19) =====
	{
		pattern: 'carrefour|leclerc|auchan|lidl|picard|intermarche|super\\s*u|monoprix|franprix|g20|casino|cora|match|netto',
		categoryId: 'cat-courses',
		priority: 10
	},
	{
		pattern: 'boulangerie|boucherie|primeur|fromager|epicerie|biocoop|naturalia',
		categoryId: 'cat-courses',
		priority: 11
	},

	// ===== ALIMENTATION - Restaurant (priority 20-29) =====
	{
		pattern: 'restaurant|brasserie|bistrot|trattoria|pizzeria|creperie|le\\s+comptoir|la\\s+table|chez\\s+',
		categoryId: 'cat-restaurant',
		priority: 20
	},
	{
		pattern: 'sushi|wok|thaï|thai|chinois|japonais|indien|kebab|grec',
		categoryId: 'cat-restaurant',
		priority: 21
	},

	// ===== ALIMENTATION - Fast-food (priority 30-39) =====
	{
		pattern: 'mcdo|mcdonald|burger\\s*king|quick|kfc|subway|domino|pizza\\s*hut|five\\s*guys|starbucks',
		categoryId: 'cat-fast-food',
		priority: 30
	},

	// ===== ALIMENTATION - Bar/Café (priority 40-49) =====
	{
		pattern: 'bar\\s+|cafe\\s+|café\\s+|pub\\s+|brasserie.*biere|columbus\\s*cafe',
		categoryId: 'cat-bar-cafe',
		priority: 40
	},

	// ===== ALIMENTATION - Livraison (priority 50-59) =====
	{
		pattern: 'uber\\s*eats|deliveroo|just\\s*eat|frichti|nestor',
		categoryId: 'cat-livraison',
		priority: 50
	},

	// ===== TRANSPORT - Carburant (priority 60-69) =====
	{
		pattern: 'total\\s*energies|totalenergies|shell|bp\\s+|esso|avia|carburant|station\\s*service|essence',
		categoryId: 'cat-carburant',
		priority: 60
	},

	// ===== TRANSPORT - Péage (priority 70-79) =====
	{
		pattern: 'sanef|vinci\\s*autoroutes|aprr|area|cofiroute|peage|péage|autoroute',
		categoryId: 'cat-peage',
		priority: 70
	},

	// ===== TRANSPORT - Parking (priority 80-89) =====
	{
		pattern: 'parking|effia|indigo\\s*park|interparking|q-park|vinci\\s*park|parcmetre',
		categoryId: 'cat-parking',
		priority: 80
	},

	// ===== TRANSPORT - Transports en commun (priority 90-99) =====
	{
		pattern: 'sncf|ratp|navigo|transilien|metro|tramway|bus\\s+|ter\\s+|tgv|ouigo|eurostar|thalys',
		categoryId: 'cat-transports-commun',
		priority: 90
	},

	// ===== TRANSPORT - Taxi/VTC (priority 100-109) =====
	{
		pattern: 'uber(?!\\s*eats)|bolt|kapten|chauffeur|taxi|vtc|heetch|marcel',
		categoryId: 'cat-taxi-vtc',
		priority: 100
	},

	// ===== TRANSPORT - Avion (priority 110-119) =====
	{
		pattern: 'air\\s*france|easyjet|ryanair|vueling|transavia|volotea|lufthansa|british\\s*airways|klm|emirates',
		categoryId: 'cat-avion',
		priority: 110
	},

	// ===== TRANSPORT - Entretien auto (priority 120-129) =====
	{
		pattern: 'norauto|feu\\s*vert|speedy|midas|euromaster|controle\\s*technique|garage|carrosserie|vidange',
		categoryId: 'cat-entretien-auto',
		priority: 120
	},

	// ===== TRANSPORT - Location voiture (priority 130-139) =====
	{
		pattern: 'hertz|avis|europcar|sixt|enterprise|ada\\s+location|rent\\s*a\\s*car|getaround',
		categoryId: 'cat-location-voiture',
		priority: 130
	},

	// ===== LOGEMENT - Charges (priority 140-149) =====
	{
		pattern: 'edf|engie|enedis|grdf|veolia|suez|lyonnaise\\s*des\\s*eaux|saur',
		categoryId: 'cat-charges',
		priority: 140
	},

	// ===== LOGEMENT - Internet/TV (priority 150-159) =====
	{
		pattern: 'orange|sfr|bouygues\\s*telecom|free\\s*|sosh|red\\s*by|b&you|numericable|canal\\+|canal\\s*plus',
		categoryId: 'cat-internet',
		priority: 150
	},

	// ===== LOGEMENT - Assurance habitation (priority 160-169) =====
	{
		pattern: 'maif|matmut|macif|maaf|gmf|groupama|axa.*habitation|allianz.*habitation|mma.*habitation',
		categoryId: 'cat-assurance-habitation',
		priority: 160
	},

	// ===== LOGEMENT - Travaux (priority 170-179) =====
	{
		pattern: 'leroy\\s*merlin|castorama|brico\\s*depot|bricomarche|mr\\s*bricolage|point\\s*p|cedeo',
		categoryId: 'cat-travaux',
		priority: 170
	},

	// ===== LOGEMENT - Ameublement (priority 180-189) =====
	{
		pattern: 'ikea|conforama|but\\s+|maisons\\s*du\\s*monde|alinea|habitat|la\\s*redoute',
		categoryId: 'cat-ameublement',
		priority: 180
	},

	// ===== LOISIRS - Abonnements (priority 190-199) =====
	{
		pattern: 'netflix|spotify|disney\\+|disney\\s*plus|amazon\\s*prime|prime\\s*video|deezer|apple\\s*music|youtube\\s*premium|hbo|paramount',
		categoryId: 'cat-abonnements',
		priority: 190
	},

	// ===== LOISIRS - Sport (priority 200-209) =====
	{
		pattern: 'basic\\s*fit|fitness|gym|salle\\s*de\\s*sport|decathlon|go\\s*sport|intersport',
		categoryId: 'cat-sport',
		priority: 200
	},

	// ===== LOISIRS - Culture (priority 210-219) =====
	{
		pattern: 'fnac|cultura|cinema|ugc|pathe|gaumont|mk2|theatre|musee|concert|ticketmaster|eventbrite',
		categoryId: 'cat-culture',
		priority: 210
	},

	// ===== LOISIRS - Jeux (priority 220-229) =====
	{
		pattern: 'micromania|game|playstation|xbox|nintendo|steam|epic\\s*games',
		categoryId: 'cat-jeux',
		priority: 220
	},

	// ===== LOISIRS - Shopping (priority 230-239) =====
	{
		pattern: 'zara|h&m|uniqlo|primark|kiabi|celio|jules|mango|galeries\\s*lafayette|printemps|amazon(?!\\s*prime)',
		categoryId: 'cat-shopping',
		priority: 230
	},

	// ===== LOISIRS - High-tech (priority 240-249) =====
	{
		pattern: 'apple\\s*store|boulanger|darty|ldlc|materiel\\.net|backmarket|cdiscount',
		categoryId: 'cat-high-tech',
		priority: 240
	},

	// ===== SANTE - Pharmacie (priority 250-259) =====
	{
		pattern: 'pharmacie|parapharmacie|pharma',
		categoryId: 'cat-pharmacie',
		priority: 250
	},

	// ===== SANTE - Médecin (priority 260-269) =====
	{
		pattern: 'docteur|dr\\.?\\s+|medecin|médecin|generaliste|cabinet\\s*medical|consultation|doctolib',
		categoryId: 'cat-medecin',
		priority: 260
	},

	// ===== SANTE - Dentiste (priority 270-279) =====
	{
		pattern: 'dentiste|dentaire|orthodontiste',
		categoryId: 'cat-dentiste',
		priority: 270
	},

	// ===== SANTE - Opticien (priority 280-289) =====
	{
		pattern: 'opticien|optical\\s*center|krys|afflelou|atol|lissac|lunettes',
		categoryId: 'cat-opticien',
		priority: 280
	},

	// ===== SANTE - Mutuelle (priority 290-299) =====
	{
		pattern: 'mutuelle|harmonie|alan|mgen|malakoff\\s*humanis|ag2r',
		categoryId: 'cat-mutuelle',
		priority: 290
	},

	// ===== BANQUE - Frais bancaires (priority 300-309) =====
	{
		pattern: 'cotisation|frais\\s*bancaire|frais\\s*de\\s*tenue|agios|commission\\s*intervention',
		categoryId: 'cat-frais-bancaires',
		priority: 300
	},

	// ===== BANQUE - Retrait DAB (priority 310-319) =====
	{
		pattern: 'retrait\\s*dab|retrait\\s*carte|retrait\\s*especes|retrait\\s*espèces|distributeur',
		categoryId: 'cat-retrait-dab',
		priority: 310
	},

	// ===== BANQUE - Intérêts (priority 320-329) =====
	{
		pattern: 'interets\\s*crediteurs|interets\\s*débiteurs|intérêts|interets',
		categoryId: 'cat-interets',
		priority: 320
	},

	// ===== REVENUS - Salaire (priority 330-339) =====
	{
		pattern: 'salaire|vir\\s+salaire|paie|remuneration|rémunération',
		categoryId: 'cat-salaire',
		priority: 330
	},

	// ===== REVENUS - Remboursement (priority 340-349) =====
	{
		pattern: 'remboursement|rbst|remb\\.?\\s|cpam|ameli|secu\\s*sociale|securite\\s*sociale',
		categoryId: 'cat-remboursement',
		priority: 340
	},

	// ===== REVENUS - Aides (priority 350-359) =====
	{
		pattern: 'caf|apl|allocation|pole\\s*emploi|france\\s*travail|rsa|prime\\s*activite',
		categoryId: 'cat-aides',
		priority: 350
	},

	// ===== IMPOTS (priority 360-369) =====
	{
		pattern: 'dgfip|impot|impôt|tresor\\s*public|taxe\\s*fonciere|taxe\\s*habitation|prelevement\\s*a\\s*la\\s*source',
		categoryId: 'cat-ir',
		priority: 360
	},

	// ===== TRANSPORT - Assurance auto (priority 370-379) =====
	{
		pattern: 'maif.*auto|matmut.*auto|macif.*auto|maaf.*auto|axa.*auto|allianz.*auto|direct\\s*assurance',
		categoryId: 'cat-assurance-auto',
		priority: 370
	},

	// ===== EPARGNE - Virements épargne (priority 380-389) =====
	{
		pattern: 'livret\\s*a|ldds|ldd|pel|cel|compte\\s*epargne|placement',
		categoryId: 'cat-livret-a',
		priority: 380
	}
];

// =====================================================
// Seed Functions
// =====================================================

async function seedCategories(): Promise<void> {
	console.log('Inserting categories...\n');

	for (const category of CATEGORIES) {
		// Insert root category
		await execute(
			`INSERT OR REPLACE INTO categories (id, name, parent_id, icon, color, created_at)
			VALUES (?, ?, ?, ?, ?, datetime('now'))`,
			[category.id, category.name, null, category.icon, category.color]
		);
		console.log(`  [ROOT] ${category.name} (${category.icon}, ${category.color})`);

		// Insert children with same color as parent
		for (const child of category.children) {
			await execute(
				`INSERT OR REPLACE INTO categories (id, name, parent_id, icon, color, created_at)
				VALUES (?, ?, ?, ?, ?, datetime('now'))`,
				[child.id, child.name, category.id, child.icon, category.color]
			);
			console.log(`    - ${child.name} (${child.icon})`);
		}
	}

	// Count total
	const totalChildren = CATEGORIES.reduce((sum, cat) => sum + cat.children.length, 0);
	console.log(`\n  ${CATEGORIES.length} root categories inserted`);
	console.log(`  ${totalChildren} sub-categories inserted`);
}

async function seedBankCategoryMappings(): Promise<void> {
	console.log('\nInserting bank category mappings as rules...\n');

	let ruleCount = 0;

	// CE mappings (source filter: caisse_epargne)
	console.log("  Caisse d'Epargne mappings:");
	for (const [bankCategory, internalCategoryId] of Object.entries(CE_CATEGORY_MAP)) {
		const ruleId = `rule-ce-${ruleCount++}`;
		// Use exact match pattern for bank categories
		const pattern = `^${escapeRegex(bankCategory)}$`;

		await execute(
			`INSERT OR REPLACE INTO category_rules (id, category_id, pattern, priority, source_filter, is_active, created_at)
			VALUES (?, ?, ?, ?, ?, ?, datetime('now'))`,
			[ruleId, internalCategoryId, pattern, 100, 'caisse_epargne', 1]
		);
		console.log(`    "${bankCategory}" -> ${internalCategoryId}`);
	}

	// Boursorama mappings (source filter: boursorama)
	console.log('\n  Boursorama mappings:');
	for (const [bankCategory, internalCategoryId] of Object.entries(BOURSO_CATEGORY_MAP)) {
		const ruleId = `rule-bourso-${ruleCount++}`;
		const pattern = `^${escapeRegex(bankCategory)}$`;

		await execute(
			`INSERT OR REPLACE INTO category_rules (id, category_id, pattern, priority, source_filter, is_active, created_at)
			VALUES (?, ?, ?, ?, ?, ?, datetime('now'))`,
			[ruleId, internalCategoryId, pattern, 100, 'boursorama', 1]
		);
		console.log(`    "${bankCategory}" -> ${internalCategoryId}`);
	}

	console.log(`\n  ${ruleCount} bank category mapping rules inserted`);
}

async function seedRegexRules(): Promise<void> {
	console.log('\nInserting regex categorization rules (for description matching)...\n');

	let ruleCount = 0;

	// Group rules by category for cleaner output
	const rulesByCategory = new Map<string, RegexRule[]>();
	for (const rule of REGEX_RULES) {
		const existing = rulesByCategory.get(rule.categoryId) || [];
		existing.push(rule);
		rulesByCategory.set(rule.categoryId, existing);
	}

	for (const [categoryId, rules] of rulesByCategory) {
		console.log(`  ${categoryId}:`);
		for (const rule of rules) {
			const ruleId = `rule-regex-${ruleCount++}`;

			await execute(
				`INSERT OR REPLACE INTO category_rules (id, category_id, pattern, priority, source_filter, is_active, created_at)
				VALUES (?, ?, ?, ?, ?, ?, datetime('now'))`,
				[ruleId, rule.categoryId, rule.pattern, rule.priority, null, 1]
			);
			console.log(`    [p${rule.priority}] /${rule.pattern.substring(0, 50)}${rule.pattern.length > 50 ? '...' : ''}/i`);
		}
	}

	console.log(`\n  ${ruleCount} regex categorization rules inserted`);
}

function escapeRegex(str: string): string {
	return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

async function verifySeededData(): Promise<void> {
	console.log('\nVerification...\n');

	// Count categories
	const rootResult = await execute('SELECT COUNT(*) as count FROM categories WHERE parent_id IS NULL');
	const rootCount = (rootResult.rows[0] as unknown as { count: number }).count;

	const childResult = await execute('SELECT COUNT(*) as count FROM categories WHERE parent_id IS NOT NULL');
	const childCount = (childResult.rows[0] as unknown as { count: number }).count;

	console.log(`  Root categories: ${rootCount}`);
	console.log(`  Sub-categories: ${childCount}`);
	console.log(`  Total categories: ${rootCount + childCount}`);

	// Count rules by type
	const bankRulesResult = await execute(
		"SELECT COUNT(*) as count FROM category_rules WHERE source_filter IS NOT NULL"
	);
	const bankRulesCount = (bankRulesResult.rows[0] as unknown as { count: number }).count;

	const regexRulesResult = await execute(
		'SELECT COUNT(*) as count FROM category_rules WHERE source_filter IS NULL'
	);
	const regexRulesCount = (regexRulesResult.rows[0] as unknown as { count: number }).count;

	console.log(`  Bank category mapping rules: ${bankRulesCount}`);
	console.log(`  Regex categorization rules: ${regexRulesCount}`);
	console.log(`  Total rules: ${bankRulesCount + regexRulesCount}`);

	// Show category hierarchy
	console.log('\n  Category hierarchy:');
	const hierarchyResult = await execute(`
		SELECT
			p.name as parent_name,
			p.color as parent_color,
			c.name as child_name
		FROM categories p
		LEFT JOIN categories c ON c.parent_id = p.id
		WHERE p.parent_id IS NULL
		ORDER BY p.name, c.name
	`);

	let currentParent = '';
	for (const row of hierarchyResult.rows) {
		const r = row as unknown as { parent_name: string; parent_color: string; child_name: string | null };
		if (r.parent_name !== currentParent) {
			currentParent = r.parent_name;
			console.log(`\n    ${r.parent_name} (${r.parent_color})`);
		}
		if (r.child_name) {
			console.log(`      - ${r.child_name}`);
		}
	}
}

// =====================================================
// Main
// =====================================================

async function main(): Promise<void> {
	console.log('Seeding categories, bank mappings, and regex rules...\n');

	try {
		await seedCategories();
		await seedBankCategoryMappings();
		await seedRegexRules();
		await verifySeededData();

		console.log('\n✓ Seed completed successfully!');
	} catch (error) {
		console.error('\n✗ Seed failed:', error);
		throw error;
	} finally {
		await closeDatabase();
	}
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
