/**
 * Seed script for real estate module initial data
 *
 * This script inserts:
 * - Entities: Mathieu, Ninon, SCI IMANISA
 * - SCI shares: 500 parts each (50%/50%)
 * - Bien 1: Appartement République Rueil
 * - Loan: Prêt Modulimmo CM Challans
 * - Property ownership: 100% Mathieu
 *
 * Run with: npx tsx src/scripts/seed-real-estate.ts
 *
 * 🤖 Generated by Ralph
 */

import { execute, executeMany, closeDatabase } from '../infrastructure/database/turso';

// =====================================================
// Entity IDs
// =====================================================

const ENTITY_IDS = {
	MATHIEU: 'mathieu',
	NINON: 'ninon',
	SCI_IMANISA: 'sci-imanisa'
} as const;

const PROPERTY_IDS = {
	RUEIL_REPUBLIQUE: 'rueil-republique'
} as const;

const LOAN_IDS = {
	RUEIL: 'loan-rueil'
} as const;

// =====================================================
// Seed Functions
// =====================================================

async function seedEntities(): Promise<void> {
	console.log('👤 Inserting entities...');

	// Mathieu
	await execute(
		`INSERT OR REPLACE INTO entities (id, name, type, email, color, legal_name, siren, rcs, share_capital, creation_date, address, tax_regime)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			ENTITY_IDS.MATHIEU,
			'Mathieu',
			'person',
			'mathieu.bourmaud@gmail.com',
			'yellow',
			null,
			null,
			null,
			null,
			null,
			null,
			null
		]
	);

	// Ninon
	await execute(
		`INSERT OR REPLACE INTO entities (id, name, type, email, color, legal_name, siren, rcs, share_capital, creation_date, address, tax_regime)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			ENTITY_IDS.NINON,
			'Ninon',
			'person',
			'ninon-loquet@outlook.fr',
			'pink',
			null,
			null,
			null,
			null,
			null,
			null,
			null
		]
	);

	// SCI IMANISA
	await execute(
		`INSERT OR REPLACE INTO entities (id, name, type, email, color, legal_name, siren, rcs, share_capital, creation_date, address, tax_regime)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			ENTITY_IDS.SCI_IMANISA,
			'SCI IMANISA',
			'sci',
			null,
			'blue',
			'SCI IMANISA',
			'989290879',
			'989 290 879 Nanterre',
			1000,
			'2025-07-19',
			'21 Rue Gustave Charpentier, 92500 Rueil-Malmaison',
			'IR'
		]
	);

	console.log('  ✅ 3 entities inserted');
}

async function seedEntityShares(): Promise<void> {
	console.log('📊 Inserting SCI shares...');

	// Mathieu: 500 parts (50%)
	await execute(
		`INSERT OR REPLACE INTO entity_shares (id, sci_id, holder_id, shares_count, percentage)
		VALUES (?, ?, ?, ?, ?)`,
		['share-mathieu-imanisa', ENTITY_IDS.SCI_IMANISA, ENTITY_IDS.MATHIEU, 500, 50]
	);

	// Ninon: 500 parts (50%)
	await execute(
		`INSERT OR REPLACE INTO entity_shares (id, sci_id, holder_id, shares_count, percentage)
		VALUES (?, ?, ?, ?, ?)`,
		['share-ninon-imanisa', ENTITY_IDS.SCI_IMANISA, ENTITY_IDS.NINON, 500, 50]
	);

	console.log('  ✅ 2 SCI shares inserted (500 each, 50%/50%)');
}

async function seedProperty(): Promise<void> {
	console.log('🏠 Inserting property (Bien 1)...');

	await execute(
		`INSERT OR REPLACE INTO re_properties (
			id, name, type, category, address, city, postal_code, country,
			surface_m2, rooms, floor, dpe_rating, copro_name, copro_lots, copro_tantiemes, syndic_name,
			purchase_date, purchase_price, notary_fees, agency_fees, renovation_costs,
			estimated_value, estimated_value_date, is_rented, monthly_rent, tenant_name, lease_start_date,
			annual_copro_charges, annual_property_tax
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			PROPERTY_IDS.RUEIL_REPUBLIQUE,
			'Appartement République',
			'apartment',
			'rental_furnished',
			'67-73 avenue de la République',
			'Rueil-Malmaison',
			'92500',
			'France',
			63.45, // surface_m2
			4, // rooms
			2, // floor
			'E', // dpe_rating
			'Les Nouveaux Martinets', // copro_name
			JSON.stringify(['352', '383']), // copro_lots (lot appart + cave)
			null, // copro_tantiemes
			'Loiselet & Daigremont', // syndic_name
			'2021-09-10', // purchase_date
			375000, // purchase_price
			null, // notary_fees
			null, // agency_fees
			null, // renovation_costs
			375000, // estimated_value
			'2026-01-15', // estimated_value_date
			0, // is_rented (non loué)
			null, // monthly_rent
			null, // tenant_name
			null, // lease_start_date
			2000, // annual_copro_charges
			null // annual_property_tax
		]
	);

	console.log('  ✅ Property "Appartement République" inserted');
}

async function seedLoan(): Promise<void> {
	console.log('💰 Inserting loan...');

	await execute(
		`INSERT OR REPLACE INTO re_loans (
			id, name, property_id, bank_name, loan_number,
			principal_amount, interest_rate, duration_months, start_date, end_date, monthly_payment,
			insurance_rate, insurance_monthly, current_balance, current_balance_date, linked_account_id
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			LOAN_IDS.RUEIL,
			'Prêt Modulimmo Rueil',
			PROPERTY_IDS.RUEIL_REPUBLIQUE,
			'Crédit Mutuel Challans',
			'15519 39050 00025097901',
			392621, // principal_amount
			1.09, // interest_rate (%)
			300, // duration_months (25 years)
			'2021-10-05', // start_date
			'2046-09-05', // end_date
			1495.73, // monthly_payment
			null, // insurance_rate
			null, // insurance_monthly
			331994.82, // current_balance (CRD au 15/01/2026)
			'2026-01-15', // current_balance_date
			null // linked_account_id
		]
	);

	console.log('  ✅ Loan "Prêt Modulimmo Rueil" inserted (CRD: 331 994,82 €)');
}

async function seedPropertyOwnership(): Promise<void> {
	console.log('📝 Inserting property ownership...');

	await execute(
		`INSERT OR REPLACE INTO property_ownership (id, property_id, entity_id, percentage, acquisition_date, acquisition_type, contribution)
		VALUES (?, ?, ?, ?, ?, ?, ?)`,
		[
			'ownership-rueil-mathieu',
			PROPERTY_IDS.RUEIL_REPUBLIQUE,
			ENTITY_IDS.MATHIEU,
			100, // 100% ownership
			'2022-05-13', // partition date
			'partition',
			null
		]
	);

	console.log('  ✅ Ownership: 100% Mathieu (depuis partage 13/05/2022)');
}

async function seedLoanResponsibility(): Promise<void> {
	console.log('📋 Inserting loan responsibility...');

	await execute(
		`INSERT OR REPLACE INTO loan_responsibility (id, loan_id, entity_id, percentage)
		VALUES (?, ?, ?, ?)`,
		['resp-rueil-mathieu', LOAN_IDS.RUEIL, ENTITY_IDS.MATHIEU, 100]
	);

	console.log('  ✅ Loan responsibility: 100% Mathieu');
}

async function verifySeedData(): Promise<void> {
	console.log('\n📊 Verification...\n');

	// Count entities
	const entitiesResult = await execute('SELECT COUNT(*) as count FROM entities');
	const entityCount = (entitiesResult.rows[0] as unknown as { count: number }).count;
	console.log(`  Entities: ${entityCount}`);

	// Count SCI shares
	const sharesResult = await execute('SELECT COUNT(*) as count FROM entity_shares');
	const shareCount = (sharesResult.rows[0] as unknown as { count: number }).count;
	console.log(`  Entity shares: ${shareCount}`);

	// Count properties
	const propertiesResult = await execute('SELECT COUNT(*) as count FROM re_properties');
	const propertyCount = (propertiesResult.rows[0] as unknown as { count: number }).count;
	console.log(`  Properties: ${propertyCount}`);

	// Count loans
	const loansResult = await execute('SELECT COUNT(*) as count FROM re_loans');
	const loanCount = (loansResult.rows[0] as unknown as { count: number }).count;
	console.log(`  Loans: ${loanCount}`);

	// Show summary
	const summaryResult = await execute(`
		SELECT
			COALESCE(SUM(p.estimated_value), 0) as total_value,
			COALESCE(SUM(l.current_balance), 0) as total_debt
		FROM re_properties p
		LEFT JOIN re_loans l ON l.property_id = p.id
	`);
	const summary = summaryResult.rows[0] as unknown as { total_value: number; total_debt: number };
	const netEquity = summary.total_value - summary.total_debt;

	console.log('\n  📈 Summary:');
	console.log(`     Valeur totale: ${summary.total_value.toLocaleString('fr-FR')} €`);
	console.log(`     Dette totale:  ${summary.total_debt.toLocaleString('fr-FR')} €`);
	console.log(`     Equity nette:  ${netEquity.toLocaleString('fr-FR')} €`);
}

// =====================================================
// Main
// =====================================================

async function main(): Promise<void> {
	console.log('🚀 Seeding real estate data...\n');

	try {
		await seedEntities();
		await seedEntityShares();
		await seedProperty();
		await seedLoan();
		await seedPropertyOwnership();
		await seedLoanResponsibility();

		await verifySeedData();

		console.log('\n✅ Seed completed successfully!');
	} catch (error) {
		console.error('\n❌ Seed failed:', error);
		throw error;
	} finally {
		await closeDatabase();
	}
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
