/**
 * Seed script for data sources (bank accounts for CSV import)
 *
 * This script inserts:
 * - Isaac entity (person, child)
 * - 7 data sources for bank CSV imports:
 *   - CM Mathieu (Crédit Mutuel)
 *   - CE Perso (Caisse d'Épargne Particulier - Mathieu)
 *   - CE Joint (Caisse d'Épargne Particulier - Joint Mathieu+Ninon)
 *   - CE Livret A (Caisse d'Épargne Particulier - Mathieu)
 *   - CE SCI (Caisse d'Épargne Entreprise - SCI IMANISA)
 *   - Boursorama Isaac CC (Compte courant Isaac)
 *   - Boursorama Isaac Livret A (Isaac)
 *
 * Run with: npx tsx src/scripts/seed-data-sources.ts
 *
 * Generated by Ralph
 */

import { execute, closeDatabase } from '../infrastructure/database/turso';

// =====================================================
// Entity IDs (reusing from seed-real-estate.ts)
// =====================================================

const ENTITY_IDS = {
	MATHIEU: 'mathieu',
	NINON: 'ninon',
	SCI_IMANISA: 'sci-imanisa',
	ISAAC: 'isaac',
	JOINT_MATHIEU_NINON: 'joint-mathieu-ninon'
} as const;

// =====================================================
// Data Source IDs
// =====================================================

const DATA_SOURCE_IDS = {
	CM_MATHIEU: 'ds-cm-mathieu',
	CE_PERSO: 'ds-ce-perso',
	CE_JOINT: 'ds-ce-joint',
	CE_LIVRET_A: 'ds-ce-livret-a',
	CE_SCI: 'ds-ce-sci',
	BOURSO_ISAAC_CC: 'ds-bourso-isaac-cc',
	BOURSO_ISAAC_LIVRET_A: 'ds-bourso-isaac-livret-a'
} as const;

// =====================================================
// Seed Functions
// =====================================================

async function seedIsaacEntity(): Promise<void> {
	console.log('Creating Isaac entity...');

	await execute(
		`INSERT OR REPLACE INTO entities (id, name, type, email, color, legal_name, siren, rcs, share_capital, creation_date, address, tax_regime)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			ENTITY_IDS.ISAAC,
			'Isaac',
			'person',
			null,
			'blue',
			null,
			null,
			null,
			null,
			null,
			null,
			null
		]
	);

	console.log('  Isaac entity created (person, blue)');
}

async function seedJointEntity(): Promise<void> {
	console.log('Creating Joint Mathieu+Ninon entity...');

	await execute(
		`INSERT OR REPLACE INTO entities (id, name, type, email, color, legal_name, siren, rcs, share_capital, creation_date, address, tax_regime)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			ENTITY_IDS.JOINT_MATHIEU_NINON,
			'Joint Mathieu+Ninon',
			'joint',
			null,
			'green',
			null,
			null,
			null,
			null,
			null,
			null,
			null
		]
	);

	console.log('  Joint Mathieu+Ninon entity created (joint, green)');
}

async function seedDataSources(): Promise<void> {
	console.log('\nInserting data sources...');

	// CM Mathieu - Crédit Mutuel
	await execute(
		`INSERT OR REPLACE INTO data_sources (id, name, type, owner_entity_id, url, format, parser_key, linked_account_id, last_sync_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			DATA_SOURCE_IDS.CM_MATHIEU,
			'CM Mathieu',
			'CHECKING',
			ENTITY_IDS.MATHIEU,
			'https://www.creditmutuel.fr/cmo/fr/banque/compte/telechargement.cgi?_tabi=C&_pid=MvtsMainPage',
			'CSV',
			'credit_mutuel',
			null,
			null
		]
	);
	console.log('  CM Mathieu (credit_mutuel)');

	// CE Perso - Caisse d'Épargne Particulier
	await execute(
		`INSERT OR REPLACE INTO data_sources (id, name, type, owner_entity_id, url, format, parser_key, linked_account_id, last_sync_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			DATA_SOURCE_IDS.CE_PERSO,
			'CE Perso',
			'CHECKING',
			ENTITY_IDS.MATHIEU,
			'https://www.caisse-epargne.fr/espace-client/compte',
			'CSV',
			'caisse_epargne',
			null,
			null
		]
	);
	console.log('  CE Perso (caisse_epargne)');

	// CE Joint - Caisse d'Épargne Joint Account
	await execute(
		`INSERT OR REPLACE INTO data_sources (id, name, type, owner_entity_id, url, format, parser_key, linked_account_id, last_sync_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			DATA_SOURCE_IDS.CE_JOINT,
			'CE Joint',
			'CHECKING',
			ENTITY_IDS.JOINT_MATHIEU_NINON,
			'https://www.caisse-epargne.fr/espace-client/compte',
			'CSV',
			'caisse_epargne',
			null,
			null
		]
	);
	console.log('  CE Joint (caisse_epargne)');

	// CE Livret A - Caisse d'Épargne Livret A
	await execute(
		`INSERT OR REPLACE INTO data_sources (id, name, type, owner_entity_id, url, format, parser_key, linked_account_id, last_sync_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			DATA_SOURCE_IDS.CE_LIVRET_A,
			'CE Livret A',
			'LIVRET_A',
			ENTITY_IDS.MATHIEU,
			'https://www.caisse-epargne.fr/espace-client/compte',
			'CSV',
			'caisse_epargne',
			null,
			null
		]
	);
	console.log('  CE Livret A (caisse_epargne)');

	// CE SCI - Caisse d'Épargne Entreprise (SCI IMANISA)
	await execute(
		`INSERT OR REPLACE INTO data_sources (id, name, type, owner_entity_id, url, format, parser_key, linked_account_id, last_sync_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			DATA_SOURCE_IDS.CE_SCI,
			'CE SCI IMANISA',
			'CHECKING',
			ENTITY_IDS.SCI_IMANISA,
			'https://www.caisse-epargne.fr/espace-entreprise/banque-en-ligne/web/mes-comptes/7504f782-7d5f-4f6e-bf36-ad3e9ea14c6d/transactions',
			'CSV',
			'caisse_epargne_entreprise',
			null,
			null
		]
	);
	console.log('  CE SCI IMANISA (caisse_epargne_entreprise)');

	// Boursorama Isaac CC - Compte Courant
	await execute(
		`INSERT OR REPLACE INTO data_sources (id, name, type, owner_entity_id, url, format, parser_key, linked_account_id, last_sync_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			DATA_SOURCE_IDS.BOURSO_ISAAC_CC,
			'Boursorama Isaac CC',
			'CHECKING',
			ENTITY_IDS.ISAAC,
			'https://clients.boursobank.com/operations/generate/2f4a1a0857e9fc898dee14c09ad809d6',
			'CSV',
			'boursorama',
			null,
			null
		]
	);
	console.log('  Boursorama Isaac CC (boursorama)');

	// Boursorama Isaac Livret A
	await execute(
		`INSERT OR REPLACE INTO data_sources (id, name, type, owner_entity_id, url, format, parser_key, linked_account_id, last_sync_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		[
			DATA_SOURCE_IDS.BOURSO_ISAAC_LIVRET_A,
			'Boursorama Isaac Livret A',
			'LIVRET_A',
			ENTITY_IDS.ISAAC,
			'https://clients.boursobank.com/operations/generate/a93b9b73a2e51cd62db59a0818d36cac',
			'CSV',
			'boursorama',
			null,
			null
		]
	);
	console.log('  Boursorama Isaac Livret A (boursorama)');

	console.log('\n  7 data sources inserted');
}

async function verifySeededData(): Promise<void> {
	console.log('\nVerification...\n');

	// Count entities
	const entitiesResult = await execute('SELECT COUNT(*) as count FROM entities');
	const entityCount = (entitiesResult.rows[0] as unknown as { count: number }).count;
	console.log(`  Entities: ${entityCount}`);

	// Count data sources
	const dataSourcesResult = await execute('SELECT COUNT(*) as count FROM data_sources');
	const dataSourceCount = (dataSourcesResult.rows[0] as unknown as { count: number }).count;
	console.log(`  Data sources: ${dataSourceCount}`);

	// List all data sources grouped by owner
	const listResult = await execute(`
		SELECT ds.name, ds.type, ds.parser_key, e.name as owner_name
		FROM data_sources ds
		JOIN entities e ON ds.owner_entity_id = e.id
		ORDER BY e.name, ds.name
	`);

	console.log('\n  Data sources by owner:');
	let currentOwner = '';
	for (const row of listResult.rows) {
		const r = row as unknown as { name: string; type: string; parser_key: string; owner_name: string };
		if (r.owner_name !== currentOwner) {
			currentOwner = r.owner_name;
			console.log(`\n    ${currentOwner}:`);
		}
		console.log(`      - ${r.name} (${r.type}, ${r.parser_key})`);
	}
}

// =====================================================
// Main
// =====================================================

async function main(): Promise<void> {
	console.log('Seeding data sources...\n');

	try {
		await seedIsaacEntity();
		await seedJointEntity();
		await seedDataSources();
		await verifySeededData();

		console.log('\n Seed completed successfully!');
	} catch (error) {
		console.error('\n Seed failed:', error);
		throw error;
	} finally {
		await closeDatabase();
	}
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
