/**
 * API endpoint for re-categorizing transactions
 *
 * POST /api/budget/recategorize - re-runs auto-categorization on all transactions
 *                                 that don't have manual categories
 *
 * 🤖 Generated by Ralph
 */

import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { CategoryRepositoryImpl } from '@infrastructure/repositories/CategoryRepository';
import { TransactionRepositoryImpl } from '@infrastructure/database/repositories/TransactionRepository';
import { AutoCategorizationService } from '@application/budget/AutoCategorizationService';

const categoryRepository = new CategoryRepositoryImpl();
const transactionRepository = new TransactionRepositoryImpl();

export const POST: RequestHandler = async () => {
	const categorizationService = new AutoCategorizationService(
		categoryRepository,
		transactionRepository
	);

	// Clear rules cache to ensure fresh rules are used
	categorizationService.clearRulesCache();

	// Run categorization on all uncategorized transactions
	const result = await categorizationService.categorizeAll();

	return json({
		categorized: result.categorized,
		skipped: result.skipped,
		manual: result.manual,
		by_source: {
			bank: result.bySource.bank,
			auto: result.bySource.auto
		}
	});
};
