/**
 * Service for mapping bank-provided categories to internal category IDs.
 *
 * This service maps categories from:
 * - Caisse d'Épargne (format: "Categorie" or "Categorie > Sous categorie")
 * - Boursorama (format: "categoryParent > category" or just "category")
 *
 * ~80% of CE/Boursorama transactions have usable bank categories.
 *
 * Generated by Ralph
 */

import { ParserKey } from '@domain/import/CSVParser';

// =====================================================
// Caisse d'Épargne Category Mappings
// =====================================================

/**
 * Maps Caisse d'Épargne categories to internal category IDs.
 * Includes both exact matches and parent-only matches.
 */
const CE_CATEGORY_MAP: Record<string, string> = {
	// Alimentation
	'Alimentation / Epicerie': 'cat-courses',
	'Alimentation - Epicerie': 'cat-courses',
	'Alimentation-Epicerie': 'cat-courses',
	Alimentation: 'cat-courses',
	Restaurant: 'cat-restaurant',
	'Restauration rapide': 'cat-fast-food',
	// Transport
	Transport: 'cat-transports-commun',
	Carburant: 'cat-carburant',
	'Auto / Moto': 'cat-entretien-auto',
	Peage: 'cat-peage',
	Péage: 'cat-peage',
	Stationnement: 'cat-parking',
	// Logement
	Logement: 'cat-loyer',
	Loyer: 'cat-loyer',
	'Energie / Eau': 'cat-charges',
	Electricite: 'cat-electricite',
	Électricité: 'cat-electricite',
	'Telecom / Internet': 'cat-internet',
	'Télécom / Internet': 'cat-internet',
	// Loisirs
	Loisirs: 'cat-sorties',
	'Culture / Sorties': 'cat-culture',
	Vacances: 'cat-vacances',
	Sport: 'cat-sport',
	// Sante
	Sante: 'cat-medecin',
	Santé: 'cat-medecin',
	Pharmacie: 'cat-pharmacie',
	Mutuelle: 'cat-mutuelle',
	// Revenus
	Salaire: 'cat-salaire',
	Revenus: 'cat-salaire',
	// Impots
	Impots: 'cat-ir',
	Impôts: 'cat-ir',
	// Banque
	'Frais bancaires': 'cat-frais-bancaires',
	'Retrait DAB': 'cat-retrait-dab',
	Virement: 'cat-virement-interne',
	// Autres
	Divers: 'cat-divers',
	'Non catégorisé': 'cat-non-categorise',
	'Non categorise': 'cat-non-categorise'
};

// =====================================================
// Boursorama Category Mappings
// =====================================================

/**
 * Maps Boursorama categories to internal category IDs.
 * Includes both exact matches and parent-only matches.
 */
const BOURSO_CATEGORY_MAP: Record<string, string> = {
	// Alimentation
	'Alimentation et restauration': 'cat-courses',
	Supermarche: 'cat-courses',
	Supermarchés: 'cat-courses',
	'Supermarchés & Epiceries': 'cat-courses',
	'Restaurants & Bars': 'cat-restaurant',
	'Fast food': 'cat-fast-food',
	Boulangerie: 'cat-courses',
	// Transport
	Transports: 'cat-transports-commun',
	'Essence & Carburant': 'cat-carburant',
	Péages: 'cat-peage',
	Parking: 'cat-parking',
	'Auto - Moto': 'cat-entretien-auto',
	'Taxis & VTC': 'cat-taxi-vtc',
	// Logement
	Logement: 'cat-loyer',
	Loyers: 'cat-loyer',
	'Energie & Services': 'cat-charges',
	'Téléphone & Internet': 'cat-internet',
	// Loisirs
	'Loisirs & Sorties': 'cat-sorties',
	Shopping: 'cat-shopping',
	'Achats & Shopping': 'cat-shopping',
	Sport: 'cat-sport',
	'Vacances & Voyages': 'cat-vacances',
	Abonnements: 'cat-abonnements',
	// Sante
	Santé: 'cat-medecin',
	Pharmacie: 'cat-pharmacie',
	// Revenus
	Salaires: 'cat-salaire',
	Revenus: 'cat-salaire',
	'Allocations & Aides': 'cat-aides',
	Remboursements: 'cat-remboursement',
	// Epargne
	Epargne: 'cat-livret-a',
	Épargne: 'cat-livret-a',
	Placements: 'cat-assurance-vie',
	// Impots
	'Impôts & Taxes': 'cat-ir',
	// Banque
	'Frais bancaires': 'cat-frais-bancaires',
	'Retrait espèces': 'cat-retrait-dab',
	Virements: 'cat-virement-interne',
	Intérêts: 'cat-interets',
	// Autres
	Divers: 'cat-divers',
	'Non catégorisé': 'cat-non-categorise',
	'Opérations non catégorisées': 'cat-non-categorise'
};

// =====================================================
// Main Export
// =====================================================

export interface CategoryMappingResult {
	/** The internal category ID, or null if no mapping found */
	categoryId: string | null;
	/** The original bank category that was matched */
	matchedCategory: string | null;
}

/**
 * Maps bank-provided categories to internal category IDs.
 *
 * Strategy:
 * 1. Try exact match on full category string (e.g., "Alimentation > Restaurant")
 * 2. Try exact match on just the category part (e.g., "Restaurant" from "Alimentation > Restaurant")
 * 3. Try exact match on just the parent part (e.g., "Alimentation" from "Alimentation > Restaurant")
 * 4. Return null if no match found
 *
 * @param rawCategory - The raw category string from the bank (e.g., "Categorie > Sous categorie")
 * @param parserKey - The parser key indicating which bank the category came from
 * @returns CategoryMappingResult with categoryId (or null) and matchedCategory
 */
export function mapBankCategory(
	rawCategory: string | undefined,
	parserKey: ParserKey
): CategoryMappingResult {
	if (!rawCategory || !rawCategory.trim()) {
		return { categoryId: null, matchedCategory: null };
	}

	const categoryMap = getCategoryMapForParser(parserKey);
	if (!categoryMap) {
		return { categoryId: null, matchedCategory: null };
	}

	const normalized = rawCategory.trim();

	// 1. Try exact match on full category string
	const exactMatch = findInMap(normalized, categoryMap);
	if (exactMatch) {
		return { categoryId: exactMatch, matchedCategory: normalized };
	}

	// 2. Parse "Parent > Child" format
	const parts = normalized.split('>').map((p) => p.trim());

	if (parts.length >= 2) {
		const parent = parts[0];
		const child = parts[parts.length - 1]; // Take the last part as the most specific

		// Try child (most specific) first
		const childMatch = findInMap(child, categoryMap);
		if (childMatch) {
			return { categoryId: childMatch, matchedCategory: child };
		}

		// Try parent
		const parentMatch = findInMap(parent, categoryMap);
		if (parentMatch) {
			return { categoryId: parentMatch, matchedCategory: parent };
		}
	}

	// 3. No match found
	return { categoryId: null, matchedCategory: null };
}

/**
 * Returns the category map for the given parser key.
 */
function getCategoryMapForParser(parserKey: ParserKey): Record<string, string> | null {
	switch (parserKey) {
		case ParserKey.CAISSE_EPARGNE:
		case ParserKey.CAISSE_EPARGNE_ENTREPRISE:
			return CE_CATEGORY_MAP;
		case ParserKey.BOURSORAMA:
			return BOURSO_CATEGORY_MAP;
		case ParserKey.CREDIT_MUTUEL:
			// Crédit Mutuel doesn't have native categories
			return null;
		default:
			return null;
	}
}

/**
 * Find a category in the map, trying various normalizations.
 */
function findInMap(category: string, map: Record<string, string>): string | null {
	const normalized = category.trim();

	// Direct match
	if (map[normalized]) {
		return map[normalized];
	}

	// Case-insensitive match
	const lowerNormalized = normalized.toLowerCase();
	for (const [key, value] of Object.entries(map)) {
		if (key.toLowerCase() === lowerNormalized) {
			return value;
		}
	}

	return null;
}

/**
 * Checks if the given parser provides native categories.
 * Use this to determine if bank category mapping should be attempted.
 */
export function parserProvidesCategories(parserKey: ParserKey): boolean {
	switch (parserKey) {
		case ParserKey.CAISSE_EPARGNE:
		case ParserKey.CAISSE_EPARGNE_ENTREPRISE:
		case ParserKey.BOURSORAMA:
			return true;
		case ParserKey.CREDIT_MUTUEL:
			return false;
		default:
			return false;
	}
}

/**
 * Gets the supported bank parser keys that provide categories.
 */
export function getSupportedBankParsers(): ParserKey[] {
	return [ParserKey.CAISSE_EPARGNE, ParserKey.CAISSE_EPARGNE_ENTREPRISE, ParserKey.BOURSORAMA];
}
