/**
 * API endpoint for listing and creating category rules
 *
 * GET /api/budget/rules - returns all rules with category info
 * POST /api/budget/rules - creates a new rule
 *
 * 🤖 Generated by Ralph
 */

import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { CategoryRepositoryImpl } from '@infrastructure/repositories/CategoryRepository';
import { CategoryRule } from '@domain/budget';
import { UniqueId } from '@domain/shared/UniqueId';

const categoryRepository = new CategoryRepositoryImpl();

export interface RuleJSON {
	id: string;
	category_id: string;
	category_name: string;
	category_icon: string;
	category_color: string;
	pattern: string;
	priority: number;
	source: string | null;
	is_active: boolean;
	created_at: string;
}

export const GET: RequestHandler = async () => {
	const rules = await categoryRepository.findAllRules();
	const categories = await categoryRepository.findAllCategories();

	// Build category lookup map
	const categoryMap = new Map(categories.map((c) => [c.id.toString(), c]));

	const rulesJson: RuleJSON[] = rules.map((rule) => {
		const category = categoryMap.get(rule.categoryId.toString());
		return {
			id: rule.id.toString(),
			category_id: rule.categoryId.toString(),
			category_name: category?.name ?? 'Unknown',
			category_icon: category?.icon ?? '❓',
			category_color: category?.color ?? '#808080',
			pattern: rule.pattern,
			priority: rule.priority,
			source: rule.source,
			is_active: rule.isActive,
			created_at: rule.createdAt.toISOString()
		};
	});

	return json(rulesJson);
};

export const POST: RequestHandler = async ({ request }) => {
	const body = await request.json();

	const { category_id, pattern, priority, source } = body as {
		category_id: string;
		pattern: string;
		priority?: number;
		source?: string | null;
	};

	if (!category_id) {
		throw error(400, 'category_id is required');
	}

	if (!pattern) {
		throw error(400, 'pattern is required');
	}

	// Validate category exists
	const category = await categoryRepository.findCategoryById(UniqueId.fromString(category_id));
	if (!category) {
		throw error(404, 'Category not found');
	}

	// Create the rule
	const ruleResult = CategoryRule.create({
		categoryId: UniqueId.fromString(category_id),
		pattern,
		priority: priority ?? 0,
		source: source ?? null
	});

	if (ruleResult.isFailure) {
		throw error(400, ruleResult.error ?? 'Failed to create rule');
	}

	const rule = ruleResult.value;
	await categoryRepository.saveRule(rule);

	return json({
		id: rule.id.toString(),
		category_id: rule.categoryId.toString(),
		category_name: category.name,
		category_icon: category.icon,
		category_color: category.color,
		pattern: rule.pattern,
		priority: rule.priority,
		source: rule.source,
		is_active: rule.isActive,
		created_at: rule.createdAt.toISOString()
	} as RuleJSON);
};
