/**
 * API endpoint for testing a rule pattern against transactions
 *
 * POST /api/budget/rules/test - tests a pattern and returns matching transactions
 *
 * 🤖 Generated by Ralph
 */

import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { execute } from '@infrastructure/database/turso';

interface MatchingTransaction {
	id: string;
	description: string;
	amount: number;
	date: string;
}

export const POST: RequestHandler = async ({ request }) => {
	const body = await request.json();
	const { pattern, limit = 20 } = body as { pattern: string; limit?: number };

	if (!pattern) {
		throw error(400, 'pattern is required');
	}

	// Validate regex pattern
	try {
		new RegExp(pattern, 'i');
	} catch {
		throw error(400, 'Invalid regex pattern');
	}

	// Fetch recent transactions and filter by pattern
	// We fetch more than needed because we filter in JS
	const result = await execute(
		`SELECT id, description, amount, date
		FROM transactions
		ORDER BY date DESC
		LIMIT 500`
	);

	const regex = new RegExp(pattern, 'i');
	const matches: MatchingTransaction[] = [];

	for (const row of result.rows) {
		const description = row.description as string;
		if (regex.test(description)) {
			matches.push({
				id: row.id as string,
				description,
				amount: row.amount as number,
				date: row.date as string
			});

			if (matches.length >= limit) {
				break;
			}
		}
	}

	return json({
		pattern,
		total_tested: result.rows.length,
		matches_count: matches.length,
		matches
	});
};
