/**
 * API endpoint for listing all categories with hierarchy
 *
 * GET /api/categories - returns all categories structured hierarchically
 *
 * 🤖 Generated by Ralph
 */

import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { CategoryRepositoryImpl } from '@infrastructure/repositories/CategoryRepository';

const categoryRepository = new CategoryRepositoryImpl();

interface CategoryJSON {
	id: string;
	name: string;
	icon: string;
	color: string;
	parent_id: string | null;
	created_at: string;
	children: CategoryJSON[];
}

export const GET: RequestHandler = async () => {
	const allCategories = await categoryRepository.findAllCategories();

	// Build hierarchical structure
	const categoryMap = new Map<string, CategoryJSON>();
	const rootCategories: CategoryJSON[] = [];

	// First pass: create all category objects
	for (const cat of allCategories) {
		categoryMap.set(cat.id.toString(), {
			id: cat.id.toString(),
			name: cat.name,
			icon: cat.icon,
			color: cat.color,
			parent_id: cat.parentId?.toString() ?? null,
			created_at: cat.createdAt.toISOString(),
			children: []
		});
	}

	// Second pass: build hierarchy
	for (const cat of allCategories) {
		const catJson = categoryMap.get(cat.id.toString())!;
		if (cat.parentId) {
			const parent = categoryMap.get(cat.parentId.toString());
			if (parent) {
				parent.children.push(catJson);
			}
		} else {
			rootCategories.push(catJson);
		}
	}

	// Sort children alphabetically
	for (const cat of categoryMap.values()) {
		cat.children.sort((a, b) => a.name.localeCompare(b.name, 'fr'));
	}

	// Sort root categories alphabetically
	rootCategories.sort((a, b) => a.name.localeCompare(b.name, 'fr'));

	return json(rootCategories);
};
