/**
 * Budget rules page server-side data loader
 * Fetches all category rules and categories for the rules management page
 *
 * 🤖 Generated by Ralph
 */

import type { PageServerLoad } from './$types';
import { CategoryRepositoryImpl } from '@infrastructure/repositories/CategoryRepository';

const categoryRepository = new CategoryRepositoryImpl();

export interface RuleJSON {
	id: string;
	category_id: string;
	category_name: string;
	category_icon: string;
	category_color: string;
	pattern: string;
	priority: number;
	source: string | null;
	is_active: boolean;
	created_at: string;
}

export interface CategoryJSON {
	id: string;
	name: string;
	icon: string;
	color: string;
	parent_id: string | null;
	children: CategoryJSON[];
}

export interface RulesPageData {
	rules: RuleJSON[];
	categories: CategoryJSON[];
}

export const load: PageServerLoad = async () => {
	const [rules, allCategories] = await Promise.all([
		categoryRepository.findAllRules(),
		categoryRepository.findAllCategories()
	]);

	// Build category lookup map
	const categoryMap = new Map(allCategories.map((c) => [c.id.toString(), c]));

	// Build hierarchical category structure for dropdown
	const categoryJSONMap = new Map<string, CategoryJSON>();
	const rootCategories: CategoryJSON[] = [];

	for (const cat of allCategories) {
		categoryJSONMap.set(cat.id.toString(), {
			id: cat.id.toString(),
			name: cat.name,
			icon: cat.icon,
			color: cat.color,
			parent_id: cat.parentId?.toString() ?? null,
			children: []
		});
	}

	for (const cat of allCategories) {
		const catJson = categoryJSONMap.get(cat.id.toString())!;
		if (cat.parentId) {
			const parent = categoryJSONMap.get(cat.parentId.toString());
			if (parent) {
				parent.children.push(catJson);
			}
		} else {
			rootCategories.push(catJson);
		}
	}

	// Sort children and root alphabetically
	for (const cat of categoryJSONMap.values()) {
		cat.children.sort((a, b) => a.name.localeCompare(b.name, 'fr'));
	}
	rootCategories.sort((a, b) => a.name.localeCompare(b.name, 'fr'));

	// Map rules to JSON format
	const rulesJson: RuleJSON[] = rules.map((rule) => {
		const category = categoryMap.get(rule.categoryId.toString());
		return {
			id: rule.id.toString(),
			category_id: rule.categoryId.toString(),
			category_name: category?.name ?? 'Unknown',
			category_icon: category?.icon ?? '❓',
			category_color: category?.color ?? '#808080',
			pattern: rule.pattern,
			priority: rule.priority,
			source: rule.source,
			is_active: rule.isActive,
			created_at: rule.createdAt.toISOString()
		};
	});

	return {
		rules: rulesJson,
		categories: rootCategories
	};
};
