<script lang="ts">
	/**
	 * Budget rules management page
	 * List, create, edit, delete, and test categorization rules
	 *
	 * 🤖 Generated by Ralph
	 */
	import { invalidateAll } from '$app/navigation';
	import type { RulesPageData, RuleJSON, CategoryJSON } from './+page.server';

	let { data }: { data: RulesPageData } = $props();

	// State
	let showAddForm = $state(false);
	let editingRule = $state<RuleJSON | null>(null);
	let testingPattern = $state<string | null>(null);
	let testResults = $state<{
		pattern: string;
		total_tested: number;
		matches_count: number;
		matches: { id: string; description: string; amount: number; date: string }[];
	} | null>(null);
	let isLoading = $state(false);
	let error = $state<string | null>(null);
	let successMessage = $state<string | null>(null);
	let showRecategorizePrompt = $state(false);

	// Form state
	let formPattern = $state('');
	let formCategoryId = $state('');
	let formPriority = $state(0);
	let formSource = $state('');

	// Flatten categories for select dropdown
	const flattenedCategories = $derived.by(() => {
		const result: { id: string; name: string; icon: string; parent_name: string | null }[] = [];

		function flatten(categories: CategoryJSON[], parentName: string | null = null) {
			for (const cat of categories) {
				result.push({
					id: cat.id,
					name: cat.name,
					icon: cat.icon,
					parent_name: parentName
				});
				if (cat.children.length > 0) {
					flatten(cat.children, cat.name);
				}
			}
		}

		flatten(data.categories);
		return result;
	});

	// Format functions
	function formatCurrency(value: number): string {
		return value.toLocaleString('fr-FR', {
			style: 'currency',
			currency: 'EUR',
			minimumFractionDigits: 2
		});
	}

	function formatDate(dateStr: string): string {
		return new Date(dateStr).toLocaleDateString('fr-FR', {
			day: '2-digit',
			month: 'short',
			year: 'numeric'
		});
	}

	// Reset form
	function resetForm() {
		formPattern = '';
		formCategoryId = '';
		formPriority = 0;
		formSource = '';
		editingRule = null;
		showAddForm = false;
		error = null;
	}

	// Open edit form
	function openEditForm(rule: RuleJSON) {
		editingRule = rule;
		formPattern = rule.pattern;
		formCategoryId = rule.category_id;
		formPriority = rule.priority;
		formSource = rule.source ?? '';
		showAddForm = true;
		error = null;
	}

	// Open add form
	function openAddForm() {
		resetForm();
		showAddForm = true;
	}

	// Save rule (create or update)
	async function saveRule() {
		if (!formPattern.trim()) {
			error = 'Le motif regex est requis';
			return;
		}

		if (!formCategoryId) {
			error = 'Une catégorie doit être sélectionnée';
			return;
		}

		// Validate regex
		try {
			new RegExp(formPattern);
		} catch {
			error = 'Le motif regex est invalide';
			return;
		}

		isLoading = true;
		error = null;

		try {
			const body = {
				category_id: formCategoryId,
				pattern: formPattern.trim(),
				priority: formPriority,
				source: formSource.trim() || null,
				is_active: true
			};

			const url = editingRule ? `/api/budget/rules/${editingRule.id}` : '/api/budget/rules';
			const method = editingRule ? 'PUT' : 'POST';

			const response = await fetch(url, {
				method,
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify(body)
			});

			if (!response.ok) {
				const data = await response.json();
				throw new Error(data.message || 'Erreur lors de la sauvegarde');
			}

			await invalidateAll();
			resetForm();
			successMessage = editingRule ? 'Règle modifiée avec succès' : 'Règle créée avec succès';
			showRecategorizePrompt = true;

			setTimeout(() => {
				successMessage = null;
			}, 5000);
		} catch (err) {
			error = err instanceof Error ? err.message : 'Une erreur est survenue';
		} finally {
			isLoading = false;
		}
	}

	// Delete rule
	async function deleteRule(rule: RuleJSON) {
		if (!confirm(`Supprimer la règle "${rule.pattern}" ?`)) {
			return;
		}

		isLoading = true;
		error = null;

		try {
			const response = await fetch(`/api/budget/rules/${rule.id}`, {
				method: 'DELETE'
			});

			if (!response.ok) {
				throw new Error('Erreur lors de la suppression');
			}

			await invalidateAll();
			successMessage = 'Règle supprimée';

			setTimeout(() => {
				successMessage = null;
			}, 3000);
		} catch (err) {
			error = err instanceof Error ? err.message : 'Une erreur est survenue';
		} finally {
			isLoading = false;
		}
	}

	// Toggle rule active state
	async function toggleRule(rule: RuleJSON) {
		isLoading = true;
		error = null;

		try {
			const response = await fetch(`/api/budget/rules/${rule.id}`, {
				method: 'PATCH'
			});

			if (!response.ok) {
				throw new Error('Erreur lors du changement de statut');
			}

			await invalidateAll();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Une erreur est survenue';
		} finally {
			isLoading = false;
		}
	}

	// Test pattern
	async function testPattern(pattern: string) {
		testingPattern = pattern;
		testResults = null;

		try {
			const response = await fetch('/api/budget/rules/test', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ pattern, limit: 20 })
			});

			if (!response.ok) {
				const data = await response.json();
				throw new Error(data.message || 'Erreur lors du test');
			}

			testResults = await response.json();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Une erreur est survenue';
			testingPattern = null;
		}
	}

	// Close test modal
	function closeTestModal() {
		testingPattern = null;
		testResults = null;
	}

	// Recategorize transactions
	async function recategorize() {
		isLoading = true;
		error = null;

		try {
			const response = await fetch('/api/budget/recategorize', {
				method: 'POST'
			});

			if (!response.ok) {
				throw new Error('Erreur lors de la recatégorisation');
			}

			const result = await response.json();
			successMessage = `Recatégorisation terminée: ${result.categorized} transactions catégorisées`;
			showRecategorizePrompt = false;

			setTimeout(() => {
				successMessage = null;
			}, 5000);
		} catch (err) {
			error = err instanceof Error ? err.message : 'Une erreur est survenue';
		} finally {
			isLoading = false;
		}
	}

	// Count stats
	const activeRulesCount = $derived(data.rules.filter((r) => r.is_active).length);
	const inactiveRulesCount = $derived(data.rules.length - activeRulesCount);
</script>

<div class="rules-page">
	<header class="page-header">
		<div class="header-left">
			<a href="/budget" class="back-link" aria-label="Retour au budget">
				<svg
					width="20"
					height="20"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
					aria-hidden="true"
				>
					<polyline points="15 18 9 12 15 6" />
				</svg>
			</a>
			<div class="header-titles">
				<h1>Règles de catégorisation</h1>
				<span class="header-subtitle">
					{data.rules.length} règle{data.rules.length > 1 ? 's' : ''}
					({activeRulesCount} active{activeRulesCount > 1 ? 's' : ''})
				</span>
			</div>
		</div>
		<button class="btn btn-primary" onclick={openAddForm}>
			<svg
				width="20"
				height="20"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				aria-hidden="true"
			>
				<line x1="12" y1="5" x2="12" y2="19" />
				<line x1="5" y1="12" x2="19" y2="12" />
			</svg>
			Ajouter
		</button>
	</header>

	<!-- Success/Error Messages -->
	{#if successMessage}
		<div class="alert alert-success">
			<svg
				width="20"
				height="20"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				aria-hidden="true"
			>
				<polyline points="20 6 9 17 4 12" />
			</svg>
			{successMessage}
			{#if showRecategorizePrompt}
				<button class="btn btn-sm btn-secondary" onclick={recategorize} disabled={isLoading}>
					Recatégoriser les transactions
				</button>
			{/if}
		</div>
	{/if}

	{#if error}
		<div class="alert alert-error">
			<svg
				width="20"
				height="20"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				aria-hidden="true"
			>
				<circle cx="12" cy="12" r="10" />
				<line x1="15" y1="9" x2="9" y2="15" />
				<line x1="9" y1="9" x2="15" y2="15" />
			</svg>
			{error}
			<button class="alert-close" onclick={() => (error = null)} aria-label="Fermer">
				<svg
					width="16"
					height="16"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
				>
					<line x1="18" y1="6" x2="6" y2="18" />
					<line x1="6" y1="6" x2="18" y2="18" />
				</svg>
			</button>
		</div>
	{/if}

	<!-- Add/Edit Form -->
	{#if showAddForm}
		<div class="form-card">
			<div class="form-header">
				<h2>{editingRule ? 'Modifier la règle' : 'Nouvelle règle'}</h2>
				<button class="btn-icon" onclick={resetForm} aria-label="Fermer">
					<svg
						width="20"
						height="20"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
					>
						<line x1="18" y1="6" x2="6" y2="18" />
						<line x1="6" y1="6" x2="18" y2="18" />
					</svg>
				</button>
			</div>

			<form class="rule-form" onsubmit={(e) => { e.preventDefault(); saveRule(); }}>
				<div class="form-group">
					<label for="pattern">Motif regex</label>
					<div class="input-with-action">
						<input
							type="text"
							id="pattern"
							bind:value={formPattern}
							placeholder="Ex: carrefour|leclerc|auchan..."
							class="form-input"
						/>
						<button
							type="button"
							class="btn btn-sm btn-ghost"
							onclick={() => formPattern && testPattern(formPattern)}
							disabled={!formPattern}
						>
							Tester
						</button>
					</div>
					<span class="form-hint">Expression régulière (insensible à la casse)</span>
				</div>

				<div class="form-group">
					<label for="category">Catégorie cible</label>
					<select id="category" bind:value={formCategoryId} class="form-select">
						<option value="">Sélectionner une catégorie...</option>
						{#each flattenedCategories as cat}
							<option value={cat.id}>
								{cat.icon} {cat.parent_name ? `${cat.parent_name} > ` : ''}{cat.name}
							</option>
						{/each}
					</select>
				</div>

				<div class="form-row">
					<div class="form-group">
						<label for="priority">Priorité</label>
						<input
							type="number"
							id="priority"
							bind:value={formPriority}
							min="0"
							max="100"
							class="form-input"
						/>
						<span class="form-hint">Plus élevé = vérifié en premier</span>
					</div>

					<div class="form-group">
						<label for="source">Filtre source (optionnel)</label>
						<input
							type="text"
							id="source"
							bind:value={formSource}
							placeholder="Ex: credit_mutuel"
							class="form-input"
						/>
						<span class="form-hint">Appliquer uniquement à cette source</span>
					</div>
				</div>

				<div class="form-actions">
					<button type="button" class="btn btn-secondary" onclick={resetForm}>
						Annuler
					</button>
					<button type="submit" class="btn btn-primary" disabled={isLoading}>
						{isLoading ? 'Enregistrement...' : editingRule ? 'Modifier' : 'Créer'}
					</button>
				</div>
			</form>
		</div>
	{/if}

	<!-- Rules List -->
	{#if data.rules.length === 0}
		<div class="empty-state">
			<div class="empty-icon" aria-hidden="true">
				<svg
					width="64"
					height="64"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="1.5"
				>
					<path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
					<polyline points="14 2 14 8 20 8" />
					<line x1="16" y1="13" x2="8" y2="13" />
					<line x1="16" y1="17" x2="8" y2="17" />
				</svg>
			</div>
			<h2>Aucune règle</h2>
			<p>Créez des règles pour catégoriser automatiquement vos transactions</p>
			<button class="btn btn-primary" onclick={openAddForm}>
				Créer une règle
			</button>
		</div>
	{:else}
		<div class="rules-list">
			{#each data.rules as rule, index}
				<div class="rule-card" class:inactive={!rule.is_active} style="--anim-delay: {index * 0.03}s">
					<div class="rule-main">
						<div class="rule-pattern">
							<code class="pattern-code">{rule.pattern}</code>
							<button
								class="btn-icon btn-test"
								onclick={() => testPattern(rule.pattern)}
								aria-label="Tester cette règle"
								title="Tester"
							>
								<svg
									width="16"
									height="16"
									viewBox="0 0 24 24"
									fill="none"
									stroke="currentColor"
									stroke-width="2"
								>
									<polygon points="5 3 19 12 5 21 5 3" />
								</svg>
							</button>
						</div>

						<div class="rule-arrow" aria-hidden="true">
							<svg
								width="20"
								height="20"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="2"
							>
								<line x1="5" y1="12" x2="19" y2="12" />
								<polyline points="12 5 19 12 12 19" />
							</svg>
						</div>

						<div class="rule-category">
							<span
								class="category-badge"
								style="background-color: {rule.category_color}20; color: {rule.category_color}"
							>
								<span class="category-icon">{rule.category_icon}</span>
								<span class="category-name">{rule.category_name}</span>
							</span>
						</div>
					</div>

					<div class="rule-meta">
						{#if rule.priority > 0}
							<span class="meta-badge priority">
								<svg
									width="12"
									height="12"
									viewBox="0 0 24 24"
									fill="none"
									stroke="currentColor"
									stroke-width="2"
								>
									<polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
								</svg>
								{rule.priority}
							</span>
						{/if}
						{#if rule.source}
							<span class="meta-badge source">
								{rule.source}
							</span>
						{/if}
						<span class="meta-date">
							{formatDate(rule.created_at)}
						</span>
					</div>

					<div class="rule-actions">
						<label class="toggle-switch" title={rule.is_active ? 'Désactiver' : 'Activer'}>
							<input
								type="checkbox"
								checked={rule.is_active}
								onchange={() => toggleRule(rule)}
								disabled={isLoading}
							/>
							<span class="toggle-slider"></span>
						</label>
						<button
							class="btn-icon"
							onclick={() => openEditForm(rule)}
							aria-label="Modifier"
							title="Modifier"
						>
							<svg
								width="18"
								height="18"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="2"
							>
								<path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
								<path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
							</svg>
						</button>
						<button
							class="btn-icon btn-danger"
							onclick={() => deleteRule(rule)}
							aria-label="Supprimer"
							title="Supprimer"
							disabled={isLoading}
						>
							<svg
								width="18"
								height="18"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="2"
							>
								<polyline points="3 6 5 6 21 6" />
								<path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
							</svg>
						</button>
					</div>
				</div>
			{/each}
		</div>
	{/if}

	<!-- Test Results Modal -->
	{#if testingPattern}
		<!-- svelte-ignore a11y_click_events_have_key_events a11y_interactive_supports_focus -->
		<div class="modal-overlay" onclick={closeTestModal} role="presentation">
			<div
				class="modal"
				onclick={(e) => e.stopPropagation()}
				role="dialog"
				aria-modal="true"
				aria-labelledby="test-modal-title"
			>
				<div class="modal-header">
					<h2 id="test-modal-title">
						Test du motif
					</h2>
					<button class="btn-icon" onclick={closeTestModal} aria-label="Fermer">
						<svg
							width="20"
							height="20"
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
						>
							<line x1="18" y1="6" x2="6" y2="18" />
							<line x1="6" y1="6" x2="18" y2="18" />
						</svg>
					</button>
				</div>

				<div class="modal-body">
					<code class="test-pattern">{testingPattern}</code>

					{#if !testResults}
						<div class="loading-state">
							<div class="spinner" aria-hidden="true"></div>
							<span>Recherche des transactions...</span>
						</div>
					{:else if testResults.matches.length === 0}
						<div class="empty-matches">
							<svg
								width="48"
								height="48"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="1.5"
								aria-hidden="true"
							>
								<circle cx="11" cy="11" r="8" />
								<line x1="21" y1="21" x2="16.65" y2="16.65" />
							</svg>
							<span>Aucune transaction ne correspond</span>
							<span class="empty-hint">{testResults.total_tested} transactions analysées</span>
						</div>
					{:else}
						<div class="matches-summary">
							<span class="matches-count">{testResults.matches_count}</span>
							correspondance{testResults.matches_count > 1 ? 's' : ''} trouvée{testResults.matches_count > 1 ? 's' : ''}
							<span class="matches-hint">sur {testResults.total_tested} transactions récentes</span>
						</div>

						<div class="matches-list">
							{#each testResults.matches as match}
								<div class="match-item">
									<div class="match-description">{match.description}</div>
									<div class="match-details">
										<span class="match-amount" class:negative={match.amount < 0}>
											{formatCurrency(match.amount)}
										</span>
										<span class="match-date">{formatDate(match.date)}</span>
									</div>
								</div>
							{/each}
						</div>
					{/if}
				</div>

				<div class="modal-footer">
					<button class="btn btn-secondary" onclick={closeTestModal}>
						Fermer
					</button>
				</div>
			</div>
		</div>
	{/if}
</div>

<style>
	.rules-page {
		max-width: var(--content-max-width);
		margin: 0 auto;
		display: flex;
		flex-direction: column;
		gap: var(--spacing-5);
	}

	/* Header */
	.page-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		gap: var(--spacing-4);
		animation: fadeInUp 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) forwards;
	}

	.header-left {
		display: flex;
		align-items: center;
		gap: var(--spacing-3);
	}

	.back-link {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 36px;
		height: 36px;
		border-radius: var(--radius-md);
		color: var(--color-text-muted);
		transition: background-color var(--transition-fast), color var(--transition-fast);
	}

	.back-link:hover {
		background: var(--color-bg-subtle);
		color: var(--color-text-primary);
	}

	.header-titles h1 {
		font-size: var(--font-size-2xl);
		font-weight: var(--font-weight-bold);
		color: var(--color-text-primary);
		letter-spacing: var(--letter-spacing-tight);
	}

	.header-subtitle {
		font-size: var(--font-size-sm);
		color: var(--color-text-muted);
	}

	/* Buttons */
	.btn {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		gap: var(--spacing-2);
		padding: var(--spacing-2) var(--spacing-4);
		border-radius: var(--radius-md);
		font-size: var(--font-size-sm);
		font-weight: var(--font-weight-medium);
		transition: background-color var(--transition-fast), color var(--transition-fast),
			border-color var(--transition-fast), opacity var(--transition-fast);
		cursor: pointer;
		border: none;
		min-height: 44px;
	}

	.btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.btn-primary {
		background: var(--color-primary-500);
		color: white;
	}

	.btn-primary:hover:not(:disabled) {
		background: var(--color-primary-600);
	}

	.btn-secondary {
		background: var(--color-bg-elevated);
		color: var(--color-text-primary);
		border: 1px solid var(--color-border);
	}

	.btn-secondary:hover:not(:disabled) {
		background: var(--color-bg-card-hover);
		border-color: var(--color-border-hover);
	}

	.btn-ghost {
		background: transparent;
		color: var(--color-text-muted);
	}

	.btn-ghost:hover:not(:disabled) {
		background: var(--color-bg-subtle);
		color: var(--color-text-primary);
	}

	.btn-sm {
		padding: var(--spacing-1) var(--spacing-3);
		min-height: 32px;
		font-size: var(--font-size-xs);
	}

	.btn-icon {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 36px;
		height: 36px;
		border-radius: var(--radius-md);
		background: transparent;
		color: var(--color-text-muted);
		border: none;
		cursor: pointer;
		transition: background-color var(--transition-fast), color var(--transition-fast);
	}

	.btn-icon:hover {
		background: var(--color-bg-subtle);
		color: var(--color-text-primary);
	}

	.btn-icon.btn-danger:hover {
		background: var(--color-danger-50);
		color: var(--color-danger-500);
	}

	.btn-icon.btn-test:hover {
		background: var(--color-primary-50);
		color: var(--color-primary-500);
	}

	/* Alerts */
	.alert {
		display: flex;
		align-items: center;
		gap: var(--spacing-3);
		padding: var(--spacing-3) var(--spacing-4);
		border-radius: var(--radius-lg);
		font-size: var(--font-size-sm);
		animation: fadeInUp 0.3s cubic-bezier(0.34, 1.56, 0.64, 1) forwards;
	}

	.alert-success {
		background: rgba(16, 185, 129, 0.1);
		color: var(--color-success-600);
		border: 1px solid var(--color-success-200);
	}

	.alert-error {
		background: var(--color-danger-50);
		color: var(--color-danger-600);
		border: 1px solid var(--color-danger-200);
	}

	.alert-close {
		margin-left: auto;
		background: transparent;
		border: none;
		padding: var(--spacing-1);
		cursor: pointer;
		color: inherit;
		opacity: 0.7;
	}

	.alert-close:hover {
		opacity: 1;
	}

	/* Form Card */
	.form-card {
		background: var(--color-bg-card);
		border-radius: var(--radius-xl);
		border: 1px solid var(--color-border);
		padding: var(--spacing-5);
		animation: fadeInUp 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) forwards;
	}

	.form-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: var(--spacing-5);
	}

	.form-header h2 {
		font-size: var(--font-size-lg);
		font-weight: var(--font-weight-semibold);
		color: var(--color-text-primary);
	}

	.rule-form {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-4);
	}

	.form-group {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-1);
	}

	.form-group label {
		font-size: var(--font-size-sm);
		font-weight: var(--font-weight-medium);
		color: var(--color-text-secondary);
	}

	.form-input,
	.form-select {
		width: 100%;
		padding: var(--spacing-3);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-md);
		font-size: var(--font-size-base);
		color: var(--color-text-primary);
		background: var(--color-bg-elevated);
		transition: border-color var(--transition-fast), box-shadow var(--transition-fast);
	}

	.form-input:focus,
	.form-select:focus {
		outline: none;
		border-color: var(--color-primary-500);
		box-shadow: 0 0 0 3px rgba(250, 128, 114, 0.15);
	}

	.form-hint {
		font-size: var(--font-size-xs);
		color: var(--color-text-muted);
	}

	.input-with-action {
		display: flex;
		gap: var(--spacing-2);
	}

	.input-with-action .form-input {
		flex: 1;
	}

	.form-row {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: var(--spacing-4);
	}

	.form-actions {
		display: flex;
		justify-content: flex-end;
		gap: var(--spacing-3);
		margin-top: var(--spacing-2);
	}

	/* Empty State */
	.empty-state {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		padding: var(--spacing-12);
		text-align: center;
		background: var(--color-bg-card);
		border-radius: var(--radius-xl);
		border: 1px dashed var(--color-border);
		gap: var(--spacing-4);
	}

	.empty-icon {
		color: var(--color-text-muted);
		opacity: 0.5;
	}

	.empty-state h2 {
		font-size: var(--font-size-lg);
		font-weight: var(--font-weight-semibold);
		color: var(--color-text-primary);
	}

	.empty-state p {
		font-size: var(--font-size-sm);
		color: var(--color-text-muted);
		max-width: 280px;
	}

	/* Rules List */
	.rules-list {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-3);
	}

	.rule-card {
		background: var(--color-bg-card);
		border-radius: var(--radius-lg);
		border: 1px solid var(--color-border);
		padding: var(--spacing-4);
		display: flex;
		flex-direction: column;
		gap: var(--spacing-3);
		animation: fadeInUp 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) calc(0.1s + var(--anim-delay)) forwards;
		opacity: 0;
		transition: border-color var(--transition-fast), opacity var(--transition-fast);
	}

	.rule-card:hover {
		border-color: var(--color-border-hover);
	}

	.rule-card.inactive {
		opacity: 0.6;
	}

	.rule-main {
		display: flex;
		align-items: center;
		gap: var(--spacing-3);
		flex-wrap: wrap;
	}

	.rule-pattern {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
		flex: 1;
		min-width: 200px;
	}

	.pattern-code {
		font-family: var(--font-mono);
		font-size: var(--font-size-sm);
		background: var(--color-bg-subtle);
		padding: var(--spacing-1) var(--spacing-2);
		border-radius: var(--radius-sm);
		color: var(--color-text-primary);
		word-break: break-all;
	}

	.rule-arrow {
		color: var(--color-text-muted);
		flex-shrink: 0;
	}

	.rule-category {
		flex-shrink: 0;
	}

	.category-badge {
		display: inline-flex;
		align-items: center;
		gap: var(--spacing-2);
		padding: var(--spacing-1-5) var(--spacing-3);
		border-radius: var(--radius-full);
		font-size: var(--font-size-sm);
		font-weight: var(--font-weight-medium);
	}

	.category-icon {
		font-size: var(--font-size-base);
	}

	.rule-meta {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
		flex-wrap: wrap;
	}

	.meta-badge {
		display: inline-flex;
		align-items: center;
		gap: var(--spacing-1);
		padding: var(--spacing-0-5) var(--spacing-2);
		border-radius: var(--radius-sm);
		font-size: var(--font-size-xs);
		background: var(--color-bg-subtle);
		color: var(--color-text-muted);
	}

	.meta-badge.priority {
		background: var(--color-warning-50);
		color: var(--color-warning-600);
	}

	.meta-badge.source {
		font-family: var(--font-mono);
	}

	.meta-date {
		font-size: var(--font-size-xs);
		color: var(--color-text-muted);
		margin-left: auto;
	}

	.rule-actions {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
		margin-left: auto;
		padding-top: var(--spacing-2);
		border-top: 1px solid var(--color-border);
	}

	/* Toggle Switch */
	.toggle-switch {
		position: relative;
		display: inline-block;
		width: 44px;
		height: 24px;
		cursor: pointer;
	}

	.toggle-switch input {
		opacity: 0;
		width: 0;
		height: 0;
	}

	.toggle-slider {
		position: absolute;
		inset: 0;
		background-color: var(--color-bg-subtle);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-full);
		transition: background-color var(--transition-fast), border-color var(--transition-fast);
	}

	.toggle-slider::before {
		content: '';
		position: absolute;
		height: 18px;
		width: 18px;
		left: 2px;
		bottom: 2px;
		background-color: white;
		border-radius: 50%;
		transition: transform var(--transition-fast);
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
	}

	.toggle-switch input:checked + .toggle-slider {
		background-color: var(--color-success-500);
		border-color: var(--color-success-500);
	}

	.toggle-switch input:checked + .toggle-slider::before {
		transform: translateX(20px);
	}

	.toggle-switch input:focus-visible + .toggle-slider {
		box-shadow: 0 0 0 3px rgba(250, 128, 114, 0.3);
	}

	/* Modal */
	.modal-overlay {
		position: fixed;
		inset: 0;
		background: rgba(0, 0, 0, 0.5);
		display: flex;
		align-items: center;
		justify-content: center;
		padding: var(--spacing-4);
		z-index: 1000;
		animation: fadeIn 0.2s ease-out forwards;
	}

	.modal {
		background: var(--color-bg-card);
		border-radius: var(--radius-xl);
		max-width: 600px;
		width: 100%;
		max-height: 80vh;
		display: flex;
		flex-direction: column;
		animation: slideUp 0.3s cubic-bezier(0.34, 1.56, 0.64, 1) forwards;
		box-shadow: var(--shadow-xl);
	}

	.modal-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: var(--spacing-4) var(--spacing-5);
		border-bottom: 1px solid var(--color-border);
	}

	.modal-header h2 {
		font-size: var(--font-size-lg);
		font-weight: var(--font-weight-semibold);
		color: var(--color-text-primary);
	}

	.modal-body {
		padding: var(--spacing-5);
		overflow-y: auto;
		flex: 1;
		display: flex;
		flex-direction: column;
		gap: var(--spacing-4);
	}

	.modal-footer {
		padding: var(--spacing-4) var(--spacing-5);
		border-top: 1px solid var(--color-border);
		display: flex;
		justify-content: flex-end;
		gap: var(--spacing-3);
	}

	.test-pattern {
		display: block;
		font-family: var(--font-mono);
		font-size: var(--font-size-sm);
		background: var(--color-bg-subtle);
		padding: var(--spacing-3);
		border-radius: var(--radius-md);
		word-break: break-all;
	}

	.loading-state {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: var(--spacing-3);
		padding: var(--spacing-8);
		color: var(--color-text-muted);
	}

	.spinner {
		width: 32px;
		height: 32px;
		border: 3px solid var(--color-border);
		border-top-color: var(--color-primary-500);
		border-radius: 50%;
		animation: spin 0.8s linear infinite;
	}

	.empty-matches {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: var(--spacing-2);
		padding: var(--spacing-6);
		color: var(--color-text-muted);
		text-align: center;
	}

	.empty-hint {
		font-size: var(--font-size-xs);
		opacity: 0.7;
	}

	.matches-summary {
		font-size: var(--font-size-sm);
		color: var(--color-text-secondary);
	}

	.matches-count {
		font-weight: var(--font-weight-semibold);
		color: var(--color-success-500);
	}

	.matches-hint {
		color: var(--color-text-muted);
	}

	.matches-list {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-2);
		max-height: 300px;
		overflow-y: auto;
	}

	.match-item {
		display: flex;
		justify-content: space-between;
		align-items: flex-start;
		gap: var(--spacing-3);
		padding: var(--spacing-3);
		background: var(--color-bg-subtle);
		border-radius: var(--radius-md);
	}

	.match-description {
		font-size: var(--font-size-sm);
		color: var(--color-text-primary);
		flex: 1;
		word-break: break-word;
	}

	.match-details {
		display: flex;
		flex-direction: column;
		align-items: flex-end;
		gap: var(--spacing-0-5);
		flex-shrink: 0;
	}

	.match-amount {
		font-size: var(--font-size-sm);
		font-weight: var(--font-weight-medium);
		color: var(--color-text-primary);
	}

	.match-amount.negative {
		color: var(--color-danger-500);
	}

	.match-date {
		font-size: var(--font-size-xs);
		color: var(--color-text-muted);
	}

	/* Animations */
	@keyframes fadeIn {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}

	@keyframes fadeInUp {
		from {
			opacity: 0;
			transform: translateY(12px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	@keyframes slideUp {
		from {
			opacity: 0;
			transform: translateY(20px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}

	/* Responsive */
	@media (max-width: 768px) {
		.page-header {
			flex-direction: column;
			align-items: flex-start;
			gap: var(--spacing-3);
		}

		.page-header .btn {
			width: 100%;
		}

		.form-row {
			grid-template-columns: 1fr;
		}

		.rule-main {
			flex-direction: column;
			align-items: flex-start;
		}

		.rule-pattern {
			width: 100%;
		}

		.rule-arrow {
			transform: rotate(90deg);
			align-self: center;
		}

		.rule-actions {
			width: 100%;
			justify-content: flex-end;
		}

		.meta-date {
			width: 100%;
			margin-left: 0;
			margin-top: var(--spacing-1);
		}

		.modal {
			max-height: 90vh;
		}
	}

	@media (max-width: 375px) {
		.header-titles h1 {
			font-size: var(--font-size-xl);
		}

		.form-card {
			padding: var(--spacing-4);
		}

		.rule-card {
			padding: var(--spacing-3);
		}
	}

	/* Reduced motion */
	@media (prefers-reduced-motion: reduce) {
		.page-header,
		.form-card,
		.rule-card,
		.alert,
		.modal-overlay,
		.modal {
			animation: none;
		}

		.rule-card {
			opacity: 1;
		}

		.spinner {
			animation: none;
		}

		.toggle-slider,
		.toggle-slider::before {
			transition: none;
		}
	}
</style>
