<!--
	CategorySuggestion.svelte

	Popup shown after manual categorization to suggest creating a rule.
	Allows users to create regex rules from transaction descriptions.

	🤖 Generated by Ralph
-->
<script lang="ts">
	import { invalidateAll } from '$app/navigation';

	interface Category {
		id: string;
		name: string;
		icon: string;
		color: string;
	}

	interface Props {
		transactionDescription: string;
		category: Category;
		onClose: () => void;
		onRuleCreated?: () => void;
	}

	let { transactionDescription, category, onClose, onRuleCreated }: Props = $props();

	// State
	let pattern = $state('');
	let isLoading = $state(false);
	let error = $state<string | null>(null);
	let showSuccess = $state(false);
	let dontAskAgain = $state(false);

	// Check localStorage for "don't ask again" preference
	const STORAGE_KEY = 'imanisa-category-suggestion-disabled';

	// Escape special regex characters
	function escapeRegex(str: string): string {
		return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
	}

	// Extract simplified pattern from description
	function generatePattern(description: string): string {
		// Remove common transaction prefixes (dates, references, etc.)
		let cleaned = description
			.replace(/^\d{2}\/\d{2}\/\d{4}\s*/i, '') // Remove date prefixes
			.replace(/^(vir|virement|prlv|prelevement|cb|carte|cheque|chq)\s*/i, '') // Remove transaction type prefixes
			.replace(/\s*\d{2}\/\d{2}(\/\d{2,4})?\s*$/i, '') // Remove date suffixes
			.replace(/\s*\*{2,}\d+$/i, '') // Remove card number suffixes like **1234
			.replace(/\s+/g, ' ') // Normalize whitespace
			.trim();

		// If description is short, use it as-is (escaped)
		if (cleaned.length <= 20) {
			return escapeRegex(cleaned.toLowerCase());
		}

		// For longer descriptions, try to extract the merchant name
		// Take first meaningful part (before common separators)
		const parts = cleaned.split(/[\-–\/|,;:]/);
		const firstPart = parts[0].trim();

		if (firstPart.length >= 3 && firstPart.length <= 30) {
			return escapeRegex(firstPart.toLowerCase());
		}

		// Fallback: take first 3 words
		const words = cleaned.split(/\s+/).slice(0, 3);
		return escapeRegex(words.join(' ').toLowerCase());
	}

	// Initialize pattern on mount
	$effect(() => {
		pattern = generatePattern(transactionDescription);
	});

	// Check if suggestion should be shown
	function isSuggestionDisabled(): boolean {
		if (typeof localStorage === 'undefined') return false;
		return localStorage.getItem(STORAGE_KEY) === 'true';
	}

	// Save "don't ask again" preference
	function saveDontAskPreference() {
		if (typeof localStorage !== 'undefined') {
			localStorage.setItem(STORAGE_KEY, 'true');
		}
	}

	// Validate regex pattern
	function validatePattern(p: string): boolean {
		try {
			new RegExp(p, 'i');
			return true;
		} catch {
			return false;
		}
	}

	// Create the rule
	async function createRule() {
		if (!pattern.trim()) {
			error = 'Le motif est requis';
			return;
		}

		if (!validatePattern(pattern)) {
			error = 'Le motif regex est invalide';
			return;
		}

		isLoading = true;
		error = null;

		try {
			const response = await fetch('/api/budget/rules', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					category_id: category.id,
					pattern: pattern.trim(),
					priority: 50, // Medium priority for user-created rules
					source: null // Apply to all sources
				})
			});

			if (!response.ok) {
				const data = await response.json();
				throw new Error(data.message || 'Erreur lors de la création de la règle');
			}

			// Trigger recategorization
			await fetch('/api/budget/recategorize', { method: 'POST' });

			showSuccess = true;

			// Refresh data
			await invalidateAll();

			// Notify parent
			onRuleCreated?.();

			// Auto-close after success
			setTimeout(() => {
				onClose();
			}, 2000);
		} catch (err) {
			error = err instanceof Error ? err.message : 'Une erreur est survenue';
		} finally {
			isLoading = false;
		}
	}

	// Handle "don't ask again" and close
	function handleDontAsk() {
		if (dontAskAgain) {
			saveDontAskPreference();
		}
		onClose();
	}

	// Close on Escape key
	function handleKeydown(event: KeyboardEvent) {
		if (event.key === 'Escape') {
			onClose();
		}
	}

	// Export for parent to check
	export function shouldShow(): boolean {
		return !isSuggestionDisabled();
	}
</script>

<svelte:window on:keydown={handleKeydown} />

<div class="suggestion-overlay" onclick={onClose} role="presentation">
	<div
		class="suggestion-modal"
		onclick={(e) => e.stopPropagation()}
		role="dialog"
		aria-modal="true"
		aria-labelledby="suggestion-title"
	>
		{#if showSuccess}
			<div class="success-content">
				<div class="success-icon" aria-hidden="true">
					<svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
						<polyline points="20 6 9 17 4 12" />
					</svg>
				</div>
				<h2>Règle créée !</h2>
				<p>Les transactions similaires seront automatiquement catégorisées.</p>
			</div>
		{:else}
			<div class="modal-header">
				<h2 id="suggestion-title">Créer une règle ?</h2>
				<button class="btn-close" onclick={onClose} aria-label="Fermer">
					<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
						<line x1="18" y1="6" x2="6" y2="18" />
						<line x1="6" y1="6" x2="18" y2="18" />
					</svg>
				</button>
			</div>

			<div class="modal-body">
				<p class="suggestion-text">
					Voulez-vous catégoriser automatiquement les transactions similaires ?
				</p>

				<div class="category-preview">
					<span class="preview-label">Catégorie :</span>
					<span
						class="category-badge"
						style="background-color: {category.color}20; color: {category.color}"
					>
						<span class="category-icon">{category.icon}</span>
						<span class="category-name">{category.name}</span>
					</span>
				</div>

				<div class="pattern-section">
					<label for="pattern-input">Motif de recherche :</label>
					<div class="pattern-input-wrapper">
						<input
							type="text"
							id="pattern-input"
							bind:value={pattern}
							class="pattern-input"
							class:error={error && error.includes('motif')}
							placeholder="Ex: carrefour|leclerc..."
							aria-describedby="pattern-hint"
						/>
					</div>
					<span id="pattern-hint" class="pattern-hint">
						Expression régulière (insensible à la casse). Utilisez | pour plusieurs mots.
					</span>
				</div>

				<div class="original-description">
					<span class="desc-label">Transaction d'origine :</span>
					<span class="desc-value">{transactionDescription}</span>
				</div>

				{#if error}
					<div class="error-message" role="alert">
						<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
							<circle cx="12" cy="12" r="10" />
							<line x1="15" y1="9" x2="9" y2="15" />
							<line x1="9" y1="9" x2="15" y2="15" />
						</svg>
						{error}
					</div>
				{/if}
			</div>

			<div class="modal-footer">
				<label class="dont-ask-checkbox">
					<input type="checkbox" bind:checked={dontAskAgain} />
					<span>Ne plus demander</span>
				</label>

				<div class="footer-actions">
					<button class="btn btn-secondary" onclick={handleDontAsk} disabled={isLoading}>
						Non merci
					</button>
					<button class="btn btn-primary" onclick={createRule} disabled={isLoading}>
						{#if isLoading}
							<span class="loading-spinner" aria-hidden="true"></span>
						{/if}
						Créer la règle
					</button>
				</div>
			</div>
		{/if}
	</div>
</div>

<style>
	.suggestion-overlay {
		position: fixed;
		inset: 0;
		background: rgba(0, 0, 0, 0.5);
		display: flex;
		align-items: center;
		justify-content: center;
		padding: var(--spacing-4);
		z-index: 1000;
		animation: fadeIn 0.2s ease-out forwards;
	}

	.suggestion-modal {
		background: var(--color-bg-card);
		border-radius: var(--radius-xl);
		max-width: 480px;
		width: 100%;
		box-shadow: var(--shadow-xl);
		animation: slideUp 0.3s cubic-bezier(0.34, 1.56, 0.64, 1) forwards;
		overflow: hidden;
	}

	/* Header */
	.modal-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: var(--spacing-4) var(--spacing-5);
		border-bottom: 1px solid var(--color-border);
	}

	.modal-header h2 {
		font-size: var(--font-size-lg);
		font-weight: var(--font-weight-semibold);
		color: var(--color-text-primary);
		margin: 0;
	}

	.btn-close {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 36px;
		height: 36px;
		border-radius: var(--radius-md);
		background: transparent;
		color: var(--color-text-muted);
		border: none;
		cursor: pointer;
		transition: background-color var(--transition-fast), color var(--transition-fast);
	}

	.btn-close:hover {
		background: var(--color-bg-subtle);
		color: var(--color-text-primary);
	}

	/* Body */
	.modal-body {
		padding: var(--spacing-5);
		display: flex;
		flex-direction: column;
		gap: var(--spacing-4);
	}

	.suggestion-text {
		font-size: var(--font-size-sm);
		color: var(--color-text-secondary);
		margin: 0;
	}

	.category-preview {
		display: flex;
		align-items: center;
		gap: var(--spacing-3);
	}

	.preview-label {
		font-size: var(--font-size-sm);
		color: var(--color-text-muted);
	}

	.category-badge {
		display: inline-flex;
		align-items: center;
		gap: var(--spacing-2);
		padding: var(--spacing-1-5) var(--spacing-3);
		border-radius: var(--radius-full);
		font-size: var(--font-size-sm);
		font-weight: var(--font-weight-medium);
	}

	.category-icon {
		font-size: var(--font-size-base);
	}

	.pattern-section {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-2);
	}

	.pattern-section label {
		font-size: var(--font-size-sm);
		font-weight: var(--font-weight-medium);
		color: var(--color-text-secondary);
	}

	.pattern-input-wrapper {
		position: relative;
	}

	.pattern-input {
		width: 100%;
		padding: var(--spacing-3);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-md);
		font-size: var(--font-size-sm);
		font-family: var(--font-mono);
		color: var(--color-text-primary);
		background: var(--color-bg-elevated);
		transition: border-color var(--transition-fast), box-shadow var(--transition-fast);
	}

	.pattern-input:focus {
		outline: none;
		border-color: var(--color-primary-500);
		box-shadow: 0 0 0 3px rgba(250, 128, 114, 0.15);
	}

	.pattern-input.error {
		border-color: var(--color-danger-500);
	}

	.pattern-hint {
		font-size: var(--font-size-xs);
		color: var(--color-text-muted);
	}

	.original-description {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-1);
		padding: var(--spacing-3);
		background: var(--color-bg-subtle);
		border-radius: var(--radius-md);
	}

	.desc-label {
		font-size: var(--font-size-xs);
		color: var(--color-text-muted);
		text-transform: uppercase;
		letter-spacing: var(--letter-spacing-caps);
	}

	.desc-value {
		font-size: var(--font-size-sm);
		color: var(--color-text-secondary);
		word-break: break-word;
	}

	.error-message {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
		padding: var(--spacing-3);
		background: var(--color-danger-50);
		border-radius: var(--radius-md);
		font-size: var(--font-size-sm);
		color: var(--color-danger-600);
	}

	/* Footer */
	.modal-footer {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: var(--spacing-4) var(--spacing-5);
		border-top: 1px solid var(--color-border);
		gap: var(--spacing-4);
	}

	.dont-ask-checkbox {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
		font-size: var(--font-size-sm);
		color: var(--color-text-muted);
		cursor: pointer;
	}

	.dont-ask-checkbox input {
		width: 16px;
		height: 16px;
		accent-color: var(--color-primary-500);
	}

	.footer-actions {
		display: flex;
		gap: var(--spacing-3);
	}

	/* Buttons */
	.btn {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		gap: var(--spacing-2);
		padding: var(--spacing-2) var(--spacing-4);
		border-radius: var(--radius-md);
		font-size: var(--font-size-sm);
		font-weight: var(--font-weight-medium);
		cursor: pointer;
		border: none;
		min-height: 44px;
		transition: background-color var(--transition-fast), color var(--transition-fast);
	}

	.btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.btn-primary {
		background: var(--color-primary-500);
		color: white;
	}

	.btn-primary:hover:not(:disabled) {
		background: var(--color-primary-600);
	}

	.btn-secondary {
		background: var(--color-bg-elevated);
		color: var(--color-text-primary);
		border: 1px solid var(--color-border);
	}

	.btn-secondary:hover:not(:disabled) {
		background: var(--color-bg-card-hover);
		border-color: var(--color-border-hover);
	}

	.loading-spinner {
		width: 16px;
		height: 16px;
		border: 2px solid rgba(255, 255, 255, 0.3);
		border-top-color: white;
		border-radius: 50%;
		animation: spin 0.6s linear infinite;
	}

	/* Success state */
	.success-content {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: var(--spacing-4);
		padding: var(--spacing-8);
		text-align: center;
	}

	.success-icon {
		width: 72px;
		height: 72px;
		border-radius: var(--radius-full);
		background: var(--color-success-50);
		color: var(--color-success-500);
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.success-content h2 {
		font-size: var(--font-size-xl);
		font-weight: var(--font-weight-semibold);
		color: var(--color-text-primary);
		margin: 0;
	}

	.success-content p {
		font-size: var(--font-size-sm);
		color: var(--color-text-muted);
		margin: 0;
		max-width: 280px;
	}

	/* Animations */
	@keyframes fadeIn {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}

	@keyframes slideUp {
		from {
			opacity: 0;
			transform: translateY(20px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}

	/* Mobile styles */
	@media (max-width: 640px) {
		.suggestion-modal {
			max-width: none;
			margin: var(--spacing-4);
		}

		.modal-footer {
			flex-direction: column;
			gap: var(--spacing-3);
		}

		.dont-ask-checkbox {
			order: 1;
		}

		.footer-actions {
			order: 0;
			width: 100%;
			flex-direction: column-reverse;
		}

		.footer-actions .btn {
			width: 100%;
		}
	}

	/* Reduced motion */
	@media (prefers-reduced-motion: reduce) {
		.suggestion-overlay,
		.suggestion-modal {
			animation: none;
		}

		.loading-spinner {
			animation: none;
		}
	}
</style>
