<!--
	CategoryBadge.svelte

	Displays a category badge for transactions with dropdown for inline editing.
	Shows source indicator (bank=blue, auto=gray, manual=green)

	🤖 Generated by Ralph
-->
<script lang="ts">
	interface Category {
		id: string;
		name: string;
		icon: string;
		color: string;
		parent_id: string | null;
		children?: Category[];
	}

	interface Props {
		transactionId: string;
		category: Category | null;
		source: 'bank' | 'auto' | 'manual' | null;
		categories: Category[];
		onCategoryChange?: (categoryId: string) => Promise<void>;
	}

	let { transactionId, category, source, categories, onCategoryChange }: Props = $props();

	let isOpen = $state(false);
	let isLoading = $state(false);
	let dropdownRef = $state<HTMLDivElement | null>(null);

	const sourceLabels = {
		bank: 'Banque',
		auto: 'Auto',
		manual: 'Manuel'
	};

	const sourceColors = {
		bank: 'var(--color-primary-500)',
		auto: 'var(--color-text-muted)',
		manual: 'var(--color-success-500)'
	};

	function getSourceColor(): string {
		if (!source) return 'var(--color-text-muted)';
		return sourceColors[source];
	}

	function getCategoryDisplayName(): string {
		if (!category) return '?';
		// Show icon + shortened name for compact display
		return `${category.icon} ${category.name}`;
	}

	function toggleDropdown() {
		isOpen = !isOpen;
	}

	function closeDropdown() {
		isOpen = false;
	}

	async function selectCategory(cat: Category) {
		if (isLoading) return;

		isLoading = true;
		try {
			if (onCategoryChange) {
				await onCategoryChange(cat.id);
			}
			closeDropdown();
		} finally {
			isLoading = false;
		}
	}

	// Close dropdown on click outside
	function handleClickOutside(event: MouseEvent) {
		if (dropdownRef && !dropdownRef.contains(event.target as Node)) {
			closeDropdown();
		}
	}

	// Close on Escape key
	function handleKeydown(event: KeyboardEvent) {
		if (event.key === 'Escape') {
			closeDropdown();
		}
	}

	$effect(() => {
		if (isOpen) {
			document.addEventListener('click', handleClickOutside);
			document.addEventListener('keydown', handleKeydown);
		}
		return () => {
			document.removeEventListener('click', handleClickOutside);
			document.removeEventListener('keydown', handleKeydown);
		};
	});
</script>

<div class="category-badge-wrapper" bind:this={dropdownRef}>
	<button
		type="button"
		class="category-badge"
		class:uncategorized={!category}
		class:source-bank={source === 'bank'}
		class:source-auto={source === 'auto'}
		class:source-manual={source === 'manual'}
		onclick={toggleDropdown}
		aria-label={category ? `Catégorie: ${category.name}, source: ${source ? sourceLabels[source] : 'aucune'}. Cliquer pour modifier` : 'Non catégorisé. Cliquer pour assigner une catégorie'}
		aria-expanded={isOpen}
		aria-haspopup="listbox"
		title={source ? `${category?.name ?? 'Non catégorisé'} (${sourceLabels[source]})` : 'Non catégorisé'}
		style="--category-color: {category?.color ?? 'var(--color-text-muted)'}; --source-color: {getSourceColor()}"
	>
		{#if isLoading}
			<span class="loading-spinner" aria-hidden="true"></span>
		{:else}
			<span class="badge-text">{getCategoryDisplayName()}</span>
			{#if source}
				<span class="source-indicator" aria-hidden="true"></span>
			{/if}
		{/if}
	</button>

	{#if isOpen}
		<div class="dropdown" role="listbox" aria-label="Sélectionner une catégorie">
			<div class="dropdown-header">
				<span>Choisir une catégorie</span>
			</div>
			<div class="dropdown-content">
				{#each categories as parentCat}
					<div class="category-group">
						<button
							type="button"
							class="category-option parent"
							onclick={() => selectCategory(parentCat)}
							role="option"
							aria-selected={category?.id === parentCat.id}
						>
							<span class="category-icon" style="color: {parentCat.color}">{parentCat.icon}</span>
							<span class="category-name">{parentCat.name}</span>
						</button>
						{#if parentCat.children && parentCat.children.length > 0}
							{#each parentCat.children as childCat}
								<button
									type="button"
									class="category-option child"
									onclick={() => selectCategory(childCat)}
									role="option"
									aria-selected={category?.id === childCat.id}
								>
									<span class="category-icon" style="color: {childCat.color}">{childCat.icon}</span>
									<span class="category-name">{childCat.name}</span>
								</button>
							{/each}
						{/if}
					</div>
				{/each}
			</div>
		</div>
	{/if}
</div>

<style>
	.category-badge-wrapper {
		position: relative;
		display: inline-block;
	}

	.category-badge {
		display: inline-flex;
		align-items: center;
		gap: var(--spacing-1);
		padding: var(--spacing-1) var(--spacing-2);
		border-radius: var(--radius-sm);
		font-size: var(--font-size-xs);
		font-weight: var(--font-weight-medium);
		background: var(--color-bg-subtle);
		border: 1px solid var(--color-border);
		color: var(--category-color);
		cursor: pointer;
		transition: background-color var(--transition-fast), border-color var(--transition-fast);
		white-space: nowrap;
		max-width: 140px;
		min-height: 28px;
	}

	.category-badge:hover {
		background: var(--color-bg-card-hover);
		border-color: var(--color-border-hover);
	}

	.category-badge:focus-visible {
		outline: 2px solid var(--color-primary-500);
		outline-offset: 2px;
	}

	.category-badge.uncategorized {
		background: var(--color-warning-50);
		border-color: var(--color-warning-200);
		color: var(--color-warning-600);
	}

	.category-badge.uncategorized:hover {
		background: var(--color-warning-100);
		border-color: var(--color-warning-300);
	}

	.badge-text {
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.source-indicator {
		width: 6px;
		height: 6px;
		border-radius: var(--radius-full);
		background: var(--source-color);
		flex-shrink: 0;
	}

	.loading-spinner {
		width: 12px;
		height: 12px;
		border: 2px solid var(--color-border);
		border-top-color: var(--color-primary-500);
		border-radius: var(--radius-full);
		animation: spin 0.6s linear infinite;
	}

	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}

	.dropdown {
		position: absolute;
		top: 100%;
		left: 0;
		margin-top: var(--spacing-1);
		background: var(--color-bg-card);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-lg);
		box-shadow: var(--shadow-lg);
		z-index: 100;
		min-width: 220px;
		max-width: 280px;
		max-height: 320px;
		overflow: hidden;
		display: flex;
		flex-direction: column;
	}

	.dropdown-header {
		padding: var(--spacing-3) var(--spacing-4);
		border-bottom: 1px solid var(--color-border-subtle);
		font-size: var(--font-size-sm);
		font-weight: var(--font-weight-semibold);
		color: var(--color-text-secondary);
	}

	.dropdown-content {
		overflow-y: auto;
		padding: var(--spacing-2) 0;
	}

	.category-group {
		padding: 0;
	}

	.category-group:not(:last-child) {
		border-bottom: 1px solid var(--color-border-subtle);
		margin-bottom: var(--spacing-1);
		padding-bottom: var(--spacing-1);
	}

	.category-option {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
		width: 100%;
		padding: var(--spacing-2) var(--spacing-4);
		background: transparent;
		border: none;
		cursor: pointer;
		font-size: var(--font-size-sm);
		color: var(--color-text-primary);
		text-align: left;
		transition: background-color var(--transition-fast);
		min-height: 40px;
	}

	.category-option:hover {
		background: var(--color-bg-card-hover);
	}

	.category-option:focus-visible {
		outline: none;
		background: var(--color-bg-card-hover);
	}

	.category-option[aria-selected='true'] {
		background: var(--color-primary-50);
		color: var(--color-primary-600);
	}

	.category-option.parent {
		font-weight: var(--font-weight-semibold);
	}

	.category-option.child {
		padding-left: var(--spacing-8);
		font-weight: var(--font-weight-normal);
		color: var(--color-text-secondary);
	}

	.category-icon {
		font-size: var(--font-size-base);
		flex-shrink: 0;
	}

	.category-name {
		flex: 1;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	@media (prefers-reduced-motion: reduce) {
		.loading-spinner {
			animation: none;
		}
	}

	@media (max-width: 640px) {
		.dropdown {
			position: fixed;
			left: var(--spacing-4);
			right: var(--spacing-4);
			top: auto;
			bottom: var(--spacing-4);
			max-width: none;
			max-height: 50vh;
			border-radius: var(--radius-xl);
		}
	}
</style>
